import { useEffect } from "react";
import { Provider } from "react-redux";
import { configureStore } from "@reduxjs/toolkit";
import { act, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { OverlayCoordinator, useOverlayCoordinator } from "@/overlay";
import { clinkRequestsReducer, clinkRequestsActions } from "@/State/clinkRequests/slice";
import type { PendingClinkDebitSession } from "@/State/clinkRequests/types";
import { LiveDebitRequest_debit_type } from "@/Api/pub/autogenerated/ts/types";
import { useAuthRequestsModal } from "./index";

vi.mock("@ionic/react", () => import("@/overlay/ionicHooks.mock"));

vi.mock("./Debit", () => ({
	default: function DebitAuthRequest({
		dismissWithRole,
	}: {
		dismissWithRole: (role: "allow") => Promise<void>;
	}) {
		return (
			<button type="button" onClick={() => void dismissWithRole("allow")}>
				allow
			</button>
		);
	},
}));

vi.mock("./Manage", () => ({
	default: () => null,
}));

function Host() {
	useAuthRequestsModal();
	return null;
}

function Occupier({ occupy }: { occupy: boolean }) {
	const { present } = useOverlayCoordinator();
	useEffect(() => {
		if (!occupy) return;
		let dismiss: ((result: { role: "confirm" }) => void) | undefined;
		void present<{ role: "confirm" }>((d) => {
			dismiss = d;
			return <button type="button" onClick={() => dismiss?.({ role: "confirm" })}>busy</button>;
		});
	}, [occupy, present]);
	return null;
}

function debitSession(requestId = "debit-1"): PendingClinkDebitSession {
	return {
		kind: "debit",
		request: {
			npub: "npub-app",
			request_id: requestId,
			debit: {
				type: LiveDebitRequest_debit_type.INVOICE,
				invoice: "lnbc1test",
			},
		},
		source: { sourceId: "source-1" } as PendingClinkDebitSession["source"],
	};
}

function renderHost(occupy = false) {
	const store = configureStore({
		reducer: { clinkRequests: clinkRequestsReducer },
	});
	render(
		<Provider store={store}>
			<OverlayCoordinator>
				<Occupier occupy={occupy} />
				<Host />
			</OverlayCoordinator>
		</Provider>,
	);
	return store;
}

describe("useAuthRequestsModal", () => {
	it("presents a claimed session and clears it on dismiss", async () => {
		const store = renderHost();
		act(() => {
			store.dispatch(clinkRequestsActions.claimPendingClinkRequestSession(debitSession()));
		});

		expect(await screen.findByRole("button", { name: "allow" })).toBeTruthy();

		await userEvent.click(screen.getByRole("button", { name: "allow" }));

		expect(store.getState().clinkRequests.pendingClinkRequestSession).toBeNull();
		expect(screen.queryByRole("button", { name: "allow" })).toBeNull();
	});

	it("waits while the overlay is occupied, then presents", async () => {
		const store = renderHost(true);

		act(() => {
			store.dispatch(clinkRequestsActions.claimPendingClinkRequestSession(debitSession()));
		});

		expect(screen.queryByRole("button", { name: "allow" })).toBeNull();
		expect(store.getState().clinkRequests.pendingClinkRequestSession).not.toBeNull();

		await userEvent.click(await screen.findByRole("button", { name: "busy" }));

		expect(await screen.findByRole("button", { name: "allow" })).toBeTruthy();
		expect(store.getState().clinkRequests.pendingClinkRequestSession).not.toBeNull();
	});
});
