import { useEffect, useState } from "react";
import { getNostrClient } from "@/Api/nostr";
import * as Types from "../../Api/pub/autogenerated/ts/types";
import { toast } from "react-toastify";
import { AdminRpcSource } from "@/State/scoped/backups/sources/selectors";
import { DashDialog } from "@/Layout2/Metrics/DashDialog";
import { useMempoolFeeTiers } from "@/Pages/Metrics/useMempoolFeeTiers";
import { displayPeerName } from "@/Pages/Metrics/overviewEvents";

type PolicyModal = "show" | "edit" | "close" | "confirm";

const COOP_WORD = "CLOSE";
const FORCE_WORD = "FORCE";

type EditChannelProps = {
	adminSource: AdminRpcSource;
	selectedChannel: Types.OpenChannel;
	deselect: () => void;
	startForce?: boolean;
	onClosed?: () => void;
	policyLoading?: boolean;
};

export const EditChannel = ({
	adminSource,
	selectedChannel,
	deselect,
	startForce = false,
	onClosed,
	policyLoading = false,
}: EditChannelProps) => {
	const { averageRate, hostLabel, failed } = useMempoolFeeTiers();
	const [modal, setModal] = useState<PolicyModal>(startForce ? "close" : "show");
	const [busy, setBusy] = useState(false);
	const [baseFeeMsat, setBaseFeeMsat] = useState(0);
	const [feeRatePpm, setFeeRatePpm] = useState(0);
	const [maxHtlcMsat, setMaxHtlcMsat] = useState(0);
	const [minHtlcMsat, setMinHtlcMsat] = useState(0);
	const [timeLockDelta, setTimeLockDelta] = useState(0);
	const [satsPerVByte, setSatsPerVByte] = useState("");
	const [force, setForce] = useState(startForce);
	const [feeTouched, setFeeTouched] = useState(false);
	const [confirmTyped, setConfirmTyped] = useState("");

	useEffect(() => {
		if (selectedChannel.policy) {
			setBaseFeeMsat(selectedChannel.policy.base_fee_msat);
			setFeeRatePpm(selectedChannel.policy.fee_rate_ppm);
			setMaxHtlcMsat(selectedChannel.policy.max_htlc_msat);
			setMinHtlcMsat(selectedChannel.policy.min_htlc_msat);
			setTimeLockDelta(selectedChannel.policy.timelock_delta);
		}
	}, [selectedChannel]);

	useEffect(() => {
		if (averageRate == null || feeTouched) return;
		setSatsPerVByte(String(averageRate));
	}, [averageRate, feeTouched]);

	const peer = displayPeerName(selectedChannel.label, selectedChannel.channel_id);

	const updatePolicy = async () => {
		if (!baseFeeMsat || !feeRatePpm || !maxHtlcMsat || !minHtlcMsat || !timeLockDelta) {
			toast.error("Please enter all fields");
			return;
		}
		setBusy(true);
		try {
			const client = await getNostrClient(
				{ pubkey: adminSource.lpk, relays: adminSource.relays },
				adminSource.keys
			);
			const res = await client.UpdateChannelPolicy({
				policy: {
					base_fee_msat: baseFeeMsat,
					fee_rate_ppm: feeRatePpm,
					max_htlc_msat: maxHtlcMsat,
					min_htlc_msat: minHtlcMsat,
					timelock_delta: timeLockDelta,
				},
				update: {
					type: Types.UpdateChannelPolicyRequest_update_type.CHANNEL_POINT,
					channel_point: selectedChannel.channel_point,
				},
			});
			if (res.status === "ERROR") {
				toast.error(res.reason);
				return;
			}
			toast.success("Policy updated");
			setModal("show");
		} finally {
			setBusy(false);
		}
	};

	const goConfirm = () => {
		const fee = Number(satsPerVByte);
		if (!force && (!Number.isFinite(fee) || fee <= 0)) {
			toast.error("Enter sats per vbyte");
			return;
		}
		setConfirmTyped("");
		setModal("confirm");
	};

	const closeChannel = async () => {
		const needed = force ? FORCE_WORD : COOP_WORD;
		if (confirmTyped.trim().toUpperCase() !== needed) return;
		const fee = Number(satsPerVByte);
		setBusy(true);
		try {
			const client = await getNostrClient(
				{ pubkey: adminSource.lpk, relays: adminSource.relays },
				adminSource.keys
			);
			const [txid, output] = selectedChannel.channel_point.split(":");
			const res = await client.CloseChannel({
				funding_txid: txid,
				output_index: +output,
				force,
				sat_per_v_byte: force ? 0 : fee,
			});
			if (res.status === "ERROR") {
				toast.error(res.reason);
				return;
			}
			toast.success(force ? "Force close broadcast" : "Channel closing");
			deselect();
			onClosed?.();
		} finally {
			setBusy(false);
		}
	};

	if (modal === "edit") {
		return (
			<DashDialog
				title="Update policy"
				onClose={() => setModal("show")}
				footer={
					<>
						<button type="button" className="dash-btn dash-btn-ghost" onClick={() => setModal("show")}>
							Back
						</button>
						<button type="button" className="dash-btn" disabled={busy} onClick={() => void updatePolicy()}>
							{busy ? "Saving…" : "Save policy"}
						</button>
					</>
				}
			>
				<NumberField label="Base fee msat" value={baseFeeMsat} onChange={setBaseFeeMsat} />
				<NumberField label="Fee rate ppm" value={feeRatePpm} onChange={setFeeRatePpm} />
				<NumberField label="Max HTLC msat" value={maxHtlcMsat} onChange={setMaxHtlcMsat} />
				<NumberField label="Min HTLC msat" value={minHtlcMsat} onChange={setMinHtlcMsat} />
				<NumberField label="Timelock delta" value={timeLockDelta} onChange={setTimeLockDelta} />
			</DashDialog>
		);
	}

	if (modal === "close") {
		return (
			<DashDialog
				title="Close channel"
				onClose={() => setModal("show")}
				footer={
					<>
						<button type="button" className="dash-btn dash-btn-ghost" onClick={() => setModal("show")}>
							Back
						</button>
						<button type="button" className="dash-btn" onClick={goConfirm}>
							Review close
						</button>
					</>
				}
			>
				<p className="dash-field-hint">{peer}</p>
				{!force && (
					<div className="dash-field">
						<label htmlFor="close-sat-vbyte">Sat / vbyte</label>
						<input
							id="close-sat-vbyte"
							type="number"
							min={1}
							inputMode="numeric"
							value={satsPerVByte}
							onChange={(e) => {
								setFeeTouched(true);
								setSatsPerVByte(e.target.value);
							}}
						/>
						<p className="dash-field-hint">
							{failed
								? `Could not load fees from ${hostLabel}. Enter a rate.`
								: `Average from ${hostLabel}. Paid on the cooperative close.`}
						</p>
					</div>
				)}
				<label className="dash-check">
					<input type="checkbox" checked={force} onChange={(e) => setForce(e.target.checked)} />
					Force close
				</label>
				{force ? (
					<p className="dash-field-hint">
						Broadcasts your commitment now. The peer does not need to be online. Your local
						sats stay locked until the delay expires — often days. No on-chain fee picker;
						the commitment sets the fee.
					</p>
				) : (
					<p className="dash-field-hint">
						Asks the peer to settle on-chain. Use force only if they are gone.
					</p>
				)}
			</DashDialog>
		);
	}

	if (modal === "confirm") {
		const needed = force ? FORCE_WORD : COOP_WORD;
		const ready = confirmTyped.trim().toUpperCase() === needed;
		return (
			<DashDialog
				title={force ? "Confirm force close" : "Confirm close"}
				onClose={() => setModal("close")}
				footer={
					<>
						<button type="button" className="dash-btn dash-btn-ghost" onClick={() => setModal("close")}>
							Back
						</button>
						<button
							type="button"
							className="dash-btn dash-btn-danger"
							disabled={!ready || busy}
							onClick={() => void closeChannel()}
						>
							{busy ? "Closing…" : force ? "Force close" : "Close channel"}
						</button>
					</>
				}
			>
				<p className="dash-field-hint">
					{force
						? `Force-closes ${peer}. Your local balance is locked until the delay expires. This cannot be undone.`
						: `Asks ${peer} to close cooperatively. Funds return after the close transaction confirms.`}
				</p>
				<div className="dash-field dash-confirm-word">
					<label htmlFor="close-confirm">Type {needed} to confirm</label>
					<input
						id="close-confirm"
						type="text"
						autoComplete="off"
						spellCheck={false}
						value={confirmTyped}
						onChange={(e) => setConfirmTyped(e.target.value)}
					/>
				</div>
			</DashDialog>
		);
	}

	return (
		<DashDialog
			title="Channel"
			onClose={deselect}
			footer={
				<>
					<button type="button" className="dash-btn dash-btn-ghost" onClick={() => setModal("close")}>
						Close channel
					</button>
					<button type="button" className="dash-btn" onClick={() => setModal("edit")} disabled={!selectedChannel.policy}>
						{policyLoading ? "Loading fees…" : "Edit policy"}
					</button>
				</>
			}
		>
			<dl className="dash-policy">
				<PolicyRow label="Peer" value={peer} />
				<PolicyRow label="Capacity" value={`${selectedChannel.local_balance + selectedChannel.remote_balance} sats`} />
				<PolicyRow label="Local" value={`${selectedChannel.local_balance} sats`} />
				<PolicyRow label="Remote" value={`${selectedChannel.remote_balance} sats`} />
			</dl>
			{selectedChannel.policy ? (
				<dl className="dash-policy">
					<PolicyRow label="Base fee msat" value={selectedChannel.policy.base_fee_msat} />
					<PolicyRow label="Fee rate ppm" value={selectedChannel.policy.fee_rate_ppm} />
					<PolicyRow label="Max HTLC msat" value={selectedChannel.policy.max_htlc_msat} />
					<PolicyRow label="Min HTLC msat" value={selectedChannel.policy.min_htlc_msat} />
					<PolicyRow label="Timelock delta" value={selectedChannel.policy.timelock_delta} />
				</dl>
			) : (
				<p className="dash-field-hint">
					{policyLoading ? "Loading fees…" : "No policy on this channel."}
				</p>
			)}
		</DashDialog>
	);
};

function PolicyRow({ label, value }: { label: string; value: string | number }) {
	return (
		<div className="dash-policy-row">
			<dt>{label}</dt>
			<dd>{value}</dd>
		</div>
	);
}

function NumberField({
	label,
	value,
	onChange,
}: {
	label: string;
	value: number;
	onChange: (n: number) => void;
}) {
	const id = label.replace(/\s+/g, "-").toLowerCase();
	return (
		<div className="dash-field">
			<label htmlFor={id}>{label}</label>
			<input
				id={id}
				type="number"
				inputMode="numeric"
				value={Number.isFinite(value) ? value : ""}
				onChange={(e) => onChange(+e.target.value)}
			/>
		</div>
	);
}
