import type { OpenChannel } from "@/Api/pub/autogenerated/ts/types";
import { displayPeerName } from "@/Pages/Metrics/overviewEvents";

export type ListedChannel = {
	avatar: string;
	name: string;
	channel: OpenChannel;
};

export function listedFromOpenChannels(channels: OpenChannel[]) {
	let max = 0;
	const active: ListedChannel[] = [];
	const offline: ListedChannel[] = [];
	for (const c of channels) {
		max = Math.max(max, c.local_balance, c.remote_balance);
		const listed = {
			avatar: channelRoboAvatarUrl(c),
			name: displayPeerName(c.label, c.channel_id),
			channel: c,
		};
		if (c.active) active.push(listed);
		else offline.push(listed);
	}
	return { active, offline, max };
}

export function channelRoboAvatarUrl(channel: OpenChannel): string {
	const seed =
		channel.channel_id?.trim() ||
		channel.channel_point?.trim() ||
		channel.label?.trim() ||
		"channel";
	return `https://robohash.org/${encodeURIComponent(seed)}.png?bgset=bg1`;
}
