import { PushNotificationEnvelope } from "@/Api/pub/autogenerated/ts/types";


const DB_NAME = "_shockwallet";
const STORE_NAME = "_ionickv";
const ENVELOPE_KEY = "push-envelope";


async function openDB(): Promise<IDBDatabase> {
	return new Promise((resolve, reject) => {
		const request = indexedDB.open(DB_NAME);
		request.onerror = () => reject(request.error);
		request.onsuccess = () => resolve(request.result);
	});
}

export async function storePendingEnvelope(envelope: PushNotificationEnvelope): Promise<void> {
	try {
		const db = await openDB();
		const tx = db.transaction(STORE_NAME, "readwrite");
		const store = tx.objectStore(STORE_NAME);

		// Store as JSON string (same format as Ionic Storage)
		store.put(JSON.stringify(envelope), ENVELOPE_KEY);

		await new Promise<void>((resolve, reject) => {
			tx.oncomplete = () => resolve();
			tx.onerror = () => reject(tx.error);
		});

		console.log("[Push IDB] Stored envelope");
	} catch (err) {
		console.error("[Push IDB] Failed to store envelope:", err);
	}
}

export async function getPendingEnvelope(): Promise<PushNotificationEnvelope | null> {
	try {
		const db = await openDB();
		const tx = db.transaction(STORE_NAME, "readonly");
		const store = tx.objectStore(STORE_NAME);

		const request = store.get(ENVELOPE_KEY);
		const value = await new Promise<string | undefined>((resolve, reject) => {
			request.onsuccess = () => resolve(request.result);
			request.onerror = () => reject(request.error);
		});

		if (!value) {
			console.log("[Push IDB] No pending envelope");
			return null;
		}

		try {
			const parsed = JSON.parse(value);
			console.log("[Push IDB] Retrieved envelope");
			return parsed as PushNotificationEnvelope;
		} catch {
			console.error("[Push IDB] Failed to parse stored envelope");
			return null;
		}
	} catch (err) {
		console.error("[Push IDB] Failed to get envelope:", err);
		return null;
	}
}

export async function clearPendingEnvelope(): Promise<void> {
	try {
		const db = await openDB();
		const tx = db.transaction(STORE_NAME, "readwrite");
		const store = tx.objectStore(STORE_NAME);

		store.delete(ENVELOPE_KEY);

		await new Promise<void>((resolve, reject) => {
			tx.oncomplete = () => resolve();
			tx.onerror = () => reject(tx.error);
		});

		console.log("[Push IDB] Cleared envelope");
	} catch (err) {
		console.error("[Push IDB] Failed to clear envelope:", err);
	}
}
