import { useState } from "react"
import { Period } from "../../Components/Dropdowns/LVDropdown"
import * as Types from '../../Api/pub/autogenerated/ts/types';
import { IonButton, IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonSkeletonText, IonText } from "@ionic/react";
import PeriodSelector from "@/Components/Dropdowns/PeriodDropdown/PeriodSelector";
import { DashBoardPageChrome } from "@/Layout2/Metrics/DashBoardPageChrome";
import { DashErrorBanner } from "./DashErrorBanner";
import type { AppApiError } from "@/State/api/api";
import { useDashboardSource } from "./DashboardSourceContext";
import { AdminOperationsList } from "./adminOperationDisplay";
import { formatTableAmount } from "./metricsDataTable";
import { useGetAppsMetricsQuery, useGetEarningsOpsInfiniteQuery } from "./pubDashApi";

function periodFromSearch(): Period {
	const p = new URLSearchParams(window.location.search).get("period");
	if (p && (Object.values(Period) as string[]).includes(p)) return p as Period;
	return Period.WEEK;
}

function offsetFromSearch(): number {
	const raw = new URLSearchParams(window.location.search).get("offset");
	const n = raw != null ? parseInt(raw, 10) : 0;
	return Number.isFinite(n) ? n : 0;
}

function appActivity(app: Types.AppMetrics): number {
	return app.operation_count ?? app.operations.length
}

function earningsApps(apps: Types.AppMetrics[]): Types.AppMetrics[] {
	return apps
		.filter((app) => app.app.id !== "unlinked")
		.sort((a, b) => appActivity(b) - appActivity(a) || (b.received + b.spent) - (a.received + a.spent))
}

export default function Earnings() {
	const [period, setPeriod] = useState<Period>(periodFromSearch)
	const [offset, setOffset] = useState<number>(offsetFromSearch)
	const [showingOps, setShowingOps] = useState<string | null>(null)
	const adminSource = useDashboardSource();
	const sourceId = adminSource.sourceId;
	const { data, error, isFetching, refetch } = useGetAppsMetricsQuery({
		sourceId,
		period,
		offset,
	});
	const loading = !data && (isFetching || !error);

	const nextOffset = () => {
		if (period === Period.ALL_TIME || offset >= 0) {
			return
		}
		setOffset(offset + 1)
	}

	const prevOffset = () => {
		if (period === Period.ALL_TIME) {
			return
		}
		setOffset(offset - 1)
	}

	return (
		<DashBoardPageChrome title="Earnings">
			<PeriodSelector
				period={period}
				offset={offset}
				setPeriod={setPeriod}
				resetOffset={() => setOffset(0)}
				prevOffset={prevOffset}
				nextOffset={nextOffset}
				disabled={isFetching}
			/>
			{loading ? (
				<EarningsSkeleton />
			) : !data ? (
				<DashErrorBanner
					message={(error as AppApiError | undefined)?.message || "Failed to fetch earnings"}
					onRetry={() => void refetch()}
				/>
			) : (
				<EarningsApps
					apps={earningsApps(data.apps)}
					sourceId={sourceId}
					period={period}
					offset={offset}
					showingOps={showingOps}
					setShowingOps={setShowingOps}
				/>
			)}
		</DashBoardPageChrome>
	);

}

function EarningsApps({
	apps,
	sourceId,
	period,
	offset,
	showingOps,
	setShowingOps,
}: {
	apps: Types.AppMetrics[]
	sourceId: string
	period: Period
	offset: number
	showingOps: string | null
	setShowingOps: (appId: string | null) => void
}) {
	const openId = showingOps ?? apps.find((app) => appActivity(app) > 0)?.app.id ?? ""

	return (
		<>
			{apps.map((app) => {
				const open = openId === app.app.id
				const hasOps = appActivity(app) > 0
				return (
					<IonCard key={app.app.id} className="ion-margin-top">
						<IonCardHeader>
							<div className="dash-app-head">
								<IonCardTitle>{app.app.name}</IonCardTitle>
								{hasOps && (
									<button
										type="button"
										className="dash-ops-toggle"
										onClick={() => setShowingOps(open ? "" : app.app.id)}
									>
										{open ? "Hide" : "Show operations"}
									</button>
								)}
							</div>
						</IonCardHeader>
						<EarningsAppCard
							app={app}
							sourceId={sourceId}
							period={period}
							offset={offset}
							showing={open}
						/>
					</IonCard>
				)
			})}
		</>
	)
}

function EarningsSkeleton() {
	return (
		<>
			<IonCard className="ion-margin-top">
				<IonCardHeader>
					<IonCardTitle>
						<IonSkeletonText animated style={{ width: "36%", height: 16, margin: 0 }} />
					</IonCardTitle>
				</IonCardHeader>
				<IonCardContent>
					<IonSkeletonText animated style={{ width: "100%", height: 72, margin: 0 }} />
					<IonSkeletonText animated style={{ width: "100%", height: 36, marginTop: 12 }} />
				</IonCardContent>
			</IonCard>
			<IonCard className="ion-margin-top">
				<IonCardHeader>
					<IonCardTitle>
						<IonSkeletonText animated style={{ width: "28%", height: 16, margin: 0 }} />
					</IonCardTitle>
				</IonCardHeader>
				<IonCardContent>
					<IonSkeletonText animated style={{ width: "100%", height: 72, margin: 0 }} />
				</IonCardContent>
			</IonCard>
		</>
	);
}

function EarningsAppCard({
	app,
	sourceId,
	period,
	offset,
	showing,
}: {
	app: Types.AppMetrics
	sourceId: string
	period: Period
	offset: number
	showing: boolean
}) {
	const {
		data,
		error,
		fetchNextPage,
		hasNextPage,
		isFetching,
		isFetchingNextPage,
		refetch,
	} = useGetEarningsOpsInfiniteQuery(
		{ sourceId, period, offset, appId: app.app.id },
		{ skip: !showing },
	)
	const operations = data?.pages.flatMap((page) => page.operations) ?? []
	const opsLoading = showing && !data && (isFetching || !error)
	const count = app.operation_count ?? 0

	return (
		<IonCardContent>
			<div
				style={{
					padding: "12px",
					background: "var(--ion-color-light)",
					borderRadius: "8px",
					marginBottom: "12px",
				}}
			>
				<div style={{ display: "flex", justifyContent: "space-between", marginBottom: "6px" }}>
					<IonText color="medium">Moved</IonText>
					<IonText>
						<strong>{formatTableAmount(app.received + app.spent)} sats</strong>
					</IonText>
				</div>
				<div style={{ display: "flex", justifyContent: "space-between", marginBottom: "6px" }}>
					<IonText color="medium">Operations</IonText>
					<IonText>
						<strong>{count}</strong>
					</IonText>
				</div>
				<div style={{ display: "flex", justifyContent: "space-between" }}>
					<IonText color="medium">Earned</IonText>
					<IonText color="primary">
						<strong>{formatTableAmount(app.fees)} sats</strong>
					</IonText>
				</div>
			</div>

			{showing && count > 0 && (
				<>
					{opsLoading ? (
						<>
							<IonSkeletonText animated style={{ width: "100%", height: 36, margin: 0 }} />
							<IonSkeletonText animated style={{ width: "90%", height: 36, marginTop: 8 }} />
						</>
					) : !data ? (
						<DashErrorBanner
							message={(error as AppApiError | undefined)?.message || "Failed to load operations"}
							onRetry={() => void refetch()}
						/>
					) : (
						<AdminOperationsList operations={operations} />
					)}
					{hasNextPage && (
						<IonButton
							fill="clear"
							expand="block"
							disabled={isFetchingNextPage}
							onClick={() => void fetchNextPage()}
						>
							{isFetchingNextPage ? "Loading…" : "Load more"}
						</IonButton>
					)}
				</>
			)}

			{count === 0 && (
				<IonText color="medium">No operations</IonText>
			)}
		</IonCardContent>
	)
}
