import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { Period } from "../../Components/Dropdowns/LVDropdown"
import { getNostrClient } from "@/Api/nostr"
import { toast } from "react-toastify";
import * as Types from '../../Api/pub/autogenerated/ts/types';
import { IonButton, IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonText, useIonRouter } from "@ionic/react";
import PeriodSelector from "@/Components/Dropdowns/PeriodDropdown/PeriodSelector";
import { DashboardShell } from "@/Layout2/Metrics/DashboardShell";
import { DashErrorBanner } from "./DashErrorBanner";
import { useAppSelector } from "@/State/store/hooks";
import { selectAdminSourceViews } from "@/State/scoped/backups/sources/selectors";
import { selectSelectedMetricsAdminSourceId } from "@/State/runtime/slice";
import { AdminOperationsList } from "./adminOperationDisplay";
import { formatTableAmount } from "./metricsDataTable";

export default function Earnings() {
    const router = useIonRouter();

    const [period, setPeriod] = useState<Period>(Period.WEEK)
    const [offset, setOffset] = useState<number>(0)
    const admins = useAppSelector(selectAdminSourceViews);
    const selectedId = useAppSelector(selectSelectedMetricsAdminSourceId);
    const adminSource = useMemo(
        () => admins.find(a => a.sourceId === selectedId),
        [admins, selectedId]
    )!;

    const [metrics, setMetrics] = useState<Types.AppsMetrics>()
    const [showingOps, setShowingOps] = useState("")
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)

    const fetchGen = useRef(0);

    const fetchMetrics = useCallback(async () => {
        const gen = ++fetchGen.current;
        setError(null);
        setLoading(true);
        try {
            const client = await getNostrClient(
                { pubkey: adminSource.lpk, relays: adminSource.relays },
                adminSource.keys
            );
            if (gen !== fetchGen.current) return;
            const periodRange = getUnixTimeRange(period, offset);
            const res = await client.GetAppsMetrics({ ...periodRange, include_operations: true })
            if (gen !== fetchGen.current) return;
            if (res.status !== 'OK') {
                setError(res.reason || "Failed to fetch earnings");
                toast.error(res.reason);
                return;
            }
            setMetrics(res);
        } catch (e) {
            if (gen !== fetchGen.current) return;
            console.error(e);
            const msg = e instanceof Error ? e.message : "Failed to fetch earnings";
            setError(msg);
            toast.error(msg);
        } finally {
            if (gen === fetchGen.current) setLoading(false);
        }
    }, [adminSource, offset, period]);

    useEffect(() => {
        dismissAppLoading();
        return () => { dismissAppLoading(); };
    }, []);

    useEffect(() => {
        const params = new URLSearchParams(window.location.search)
        const periodParam = params.get("period")
        const offsetParam = params.get("offset")
        if (periodParam) {
            setPeriod(periodParam as Period)
        }
        if (offsetParam) {
            setOffset(parseInt(offsetParam))
        }
    }, [])
    useEffect(() => {
        void fetchMetrics();
        return () => { fetchGen.current += 1; };
    }, [fetchMetrics])
    const nextOffset = () => {
        if (period === Period.ALL_TIME || offset >= 0) {
            return
        }
        setOffset(offset + 1)
    }

    const prevOffset = () => {
        if (period === Period.ALL_TIME) {
            return
        }
        setOffset(offset - 1)
    }

    return (
        <DashboardShell title="Earnings">
            {error && (
                <DashErrorBanner
                    message={error}
                    onRetry={() => void fetchMetrics()}
                    onChangeSource={() => router.push("/metrics/select", "back")}
                />
            )}


            {loading && <p className="dash-field-hint">Loading earnings…</p>}

            {metrics && !error && (
                <>
                    <PeriodSelector
                        period={period}
                        offset={offset}
                        setPeriod={setPeriod}
                        resetOffset={() => setOffset(0)}
                        prevOffset={prevOffset}
                        nextOffset={nextOffset}
                    />

                    {metrics.apps
                        .filter((app) => app.app.id !== "unlinked")
                        .map((app, i) => (
                        <IonCard key={i} className="ion-margin-top">
                            <IonCardHeader>
                                <IonCardTitle>{app.app.name}</IonCardTitle>
                            </IonCardHeader>

                            {!loading && (
                                <IonCardContent>
                                    <div
                                        style={{
                                            padding: "12px",
                                            background: "var(--ion-color-light)",
                                            borderRadius: "8px",
                                            marginBottom: "12px",
                                        }}
                                    >
                                        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "6px" }}>
                                            <IonText color="medium">Moved</IonText>
                                            <IonText>
                                                <strong>{formatTableAmount(app.received + app.spent)} sats</strong>
                                            </IonText>
                                        </div>
                                        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "6px" }}>
                                            <IonText color="medium">Operations</IonText>
                                            <IonText>
                                                <strong>{app.operations.length}</strong>
                                            </IonText>
                                        </div>
                                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                                            <IonText color="medium">Earned</IonText>
                                            <IonText color="primary">
                                                <strong>{formatTableAmount(app.fees)} sats</strong>
                                            </IonText>
                                        </div>
                                    </div>

                                    {app.operations.length > 0 && (
                                        <>
                                            {showingOps !== app.app.name ? (
                                                <IonButton fill="outline" expand="block" onClick={() => setShowingOps(app.app.name)}>
                                                    Show operations
                                                </IonButton>
                                            ) : (
                                                <>
                                                    <IonButton fill="outline" expand="block" onClick={() => setShowingOps("")}>
                                                        Hide operations
                                                    </IonButton>
                                                    <div className="ion-margin-top">
                                                        <AdminOperationsList operations={app.operations} />
                                                    </div>
                                                </>
                                            )}
                                        </>
                                    )}

                                    {app.operations.length === 0 && (
                                        <IonText color="medium">No operations</IonText>
                                    )}
                                </IonCardContent>
                            )}
                        </IonCard>
                    ))}
                </>
            )}
        </DashboardShell>
    );

}

export const getUnixTimeRange = (period: Period, offset: number) => {
    const now = new Date();
    let from_unix: number, to_unix: number;

    switch (period) {
        case Period.WEEK: {
            /*       const thisWeek = new Date(now.setDate(now.getDate() - now.getDay()))
                                    thisWeek.setHours(0, 0, 0, 0)
                                    console.log({ thisWeek: thisWeek.toISOString() })
                                    const thisWeekMs = thisWeek.getTime() */

            const firstDayOfWeek = new Date(new Date().setDate(now.getDate() - now.getDay() + (offset * 7))).setHours(0, 0, 0, 0);
            const lastDayOfWeek = new Date(new Date().setDate(now.getDate() - now.getDay() + 6 + (offset * 7))).setHours(23, 59, 59, 999);
            from_unix = Math.floor(firstDayOfWeek / 1000);
            to_unix = Math.floor(lastDayOfWeek / 1000);
            break;
        }

        case Period.MONTH: {
            const firstDayOfMonth = new Date(now.getFullYear(), now.getMonth() + offset, 1).getTime();
            const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1 + offset, 0).setHours(23, 59, 59, 999);
            from_unix = Math.floor(firstDayOfMonth / 1000);
            to_unix = Math.floor(lastDayOfMonth / 1000);
            break;
        }

        case Period.YEAR: {
            const firstDayOfYear = new Date(now.getFullYear() + offset, 0, 1).getTime();
            const lastDayOfYear = new Date(now.getFullYear() + offset, 11, 31).setHours(23, 59, 59, 999);
            from_unix = Math.floor(firstDayOfYear / 1000);
            to_unix = Math.floor(lastDayOfYear / 1000);
            break;
        }
        case Period.ALL_TIME:
            return undefined
    }
    console.log({ from_unix: new Date(from_unix * 1000).toISOString(), to_unix: new Date(to_unix * 1000).toISOString() })
    return { from_unix, to_unix };
}

function dismissAppLoading() {
    const el = document.querySelector("ion-loading")
    if (el && "dismiss" in el && typeof el.dismiss === "function") {
        void el.dismiss()
    }
}

