import { useMemo, useState } from "react";
import { IonSkeletonText } from "@ionic/react";
import type { LndPeer } from "@/Api/pub/autogenerated/ts/types";
import { DashBoardPageChrome } from "@/Layout2/Metrics/DashBoardPageChrome";
import { DashDialog } from "@/Layout2/Metrics/DashDialog";
import type { AppApiError } from "@/State/api/api";
import { AddPeerForm } from "./AddPeerForm";
import { ChannelOpenForm } from "./ChannelOpenForm";
import { DashErrorBanner } from "./DashErrorBanner";
import { useDashboardSource } from "./DashboardSourceContext";
import { useListPeersQuery } from "./pubDashApi";
import { useGetPubDashboardCapabilityQuery } from "./pubDashboardCapabilityApi";
import { PubUpgradeNotice } from "./PubUpgradeNotice";

export default function Peers() {
	const adminSource = useDashboardSource();
	const sourceId = adminSource.sourceId;
	const cap = useGetPubDashboardCapabilityQuery({ sourceId });
	const needsUpgrade = cap.data === "needs_upgrade";
	const capPending = !cap.data && (cap.isFetching || !cap.error);
	const [selected, setSelected] = useState<LndPeer | null>(null);
	const { data, error, isFetching, refetch } = useListPeersQuery(
		{ sourceId },
		{ skip: needsUpgrade || capPending },
	);
	const loading = !data && (isFetching || !error);
	const ordered = useMemo(() => channelPeersFirst(data ?? []), [data]);

	return (
		<DashBoardPageChrome title="Peers">
			<AddPeerForm />
			{needsUpgrade ? (
				<PubUpgradeNotice
					featureLabel="listing peers"
					onRecheck={() => void cap.refetch()}
					checking={cap.isFetching}
				/>
			) : capPending || loading ? (
				<PeerListSkeleton />
			) : !data ? (
				<DashErrorBanner
					message={(error as AppApiError | undefined)?.message || "Could not list peers"}
					onRetry={() => void refetch()}
				/>
			) : (
				<PeerList peers={ordered} onSelect={setSelected} />
			)}
			{selected && (
				<PeerDialog
					peer={selected}
					onClose={() => setSelected(null)}
					onOpened={() => setSelected(null)}
				/>
			)}
		</DashBoardPageChrome>
	);
}

function PeerList({ peers, onSelect }: { peers: LndPeer[]; onSelect: (peer: LndPeer) => void }) {
	if (peers.length === 0) {
		return <p className="dash-field-hint">No connected peers. Add one above.</p>;
	}
	return (
		<div className="dash-section">
			<div className="dash-section-head">
				<h2>Connected</h2>
				<span className="dash-section-count">{peers.length}</span>
			</div>
			<div className="dash-peer-stack">
				{peers.map((peer) => (
					<PeerRow key={peer.pubkey} peer={peer} onSelect={onSelect} />
				))}
			</div>
		</div>
	);
}

function PeerListSkeleton() {
	return (
		<div className="dash-section">
			<div className="dash-section-head">
				<h2>Connected</h2>
			</div>
			<div className="dash-peer-stack">
				<div className="dash-peer-item">
					<IonSkeletonText animated style={{ width: "42%", height: 16, margin: 0 }} />
					<IonSkeletonText animated style={{ width: "64%", height: 12, marginTop: 8 }} />
				</div>
				<div className="dash-peer-item">
					<IonSkeletonText animated style={{ width: "36%", height: 16, margin: 0 }} />
					<IonSkeletonText animated style={{ width: "58%", height: 12, marginTop: 8 }} />
				</div>
			</div>
		</div>
	);
}

function PeerRow({ peer, onSelect }: { peer: LndPeer; onSelect: (peer: LndPeer) => void }) {
	return (
		<button type="button" className="dash-peer-item" onClick={() => onSelect(peer)}>
			<div className="dash-peer-item-main">
				<div className="dash-peer-item-name">{displayName(peer)}</div>
				<div className="dash-peer-item-sub">
					{peer.address || shortPubkey(peer.pubkey)}
					{peer.alias ? ` · ${shortPubkey(peer.pubkey)}` : ""}
				</div>
			</div>
			{peer.has_channel && <span className="dash-pill is-ok">channel</span>}
		</button>
	);
}

function PeerDialog({
	peer,
	onClose,
	onOpened,
}: {
	peer: LndPeer;
	onClose: () => void;
	onOpened: () => void;
}) {
	return (
		<DashDialog title={displayName(peer)} onClose={onClose}>
			<dl className="dash-policy">
				<div className="dash-policy-row">
					<dt>Pubkey</dt>
					<dd>{peer.pubkey}</dd>
				</div>
				{peer.address && (
					<div className="dash-policy-row">
						<dt>Address</dt>
						<dd>{peer.address}</dd>
					</div>
				)}
				<div className="dash-policy-row">
					<dt>Channel</dt>
					<dd>{peer.has_channel ? "yes" : "gossip only"}</dd>
				</div>
			</dl>
			<span className="dash-section-tag">Open channel</span>
			<ChannelOpenForm
				peerLocked={peer.pubkey}
				onOpened={onOpened}
			/>
		</DashDialog>
	);
}

function channelPeersFirst(peers: LndPeer[]) {
	const withChannel: LndPeer[] = [];
	const gossip: LndPeer[] = [];
	for (const peer of peers) {
		if (peer.has_channel) withChannel.push(peer);
		else gossip.push(peer);
	}
	return [...withChannel, ...gossip];
}

function displayName(peer: LndPeer) {
	const alias = peer.alias?.trim();
	if (alias && alias !== peer.pubkey) return alias;
	return shortPubkey(peer.pubkey);
}

function shortPubkey(pubkey: string) {
	if (pubkey.length < 16) return pubkey;
	return `${pubkey.slice(0, 8)}…${pubkey.slice(-8)}`;
}
