import { getNostrClient } from "@/Api/nostr";
import {
	UpdateChannelPolicyRequest_update_type,
	type AdminNodeSettings,
	type AppsMetrics,
	type AssetsAndLiabilitiesReqV2,
	type AssetsAndLiabilitiesV2,
	type ChannelPolicy,
	type InvoiceSwapQuoteList,
	type InvoiceSwapsList,
	type LndForwardingMetrics,
	type LndGetInfoResponse,
	type LndMetrics,
	type LndPeer,
	type LndUtxo,
	type OpenChannel,
	type TransactionSwapQuoteList,
	type TxSwapsList,
	type UpdateAdminNodeSettingsRequest,
	type UserOperation,
	type UsersAdminInfo,
} from "@/Api/pub/autogenerated/ts/types";
import type { Period } from "@/Components/Dropdowns/LVDropdown";
import { appApi, appApiCaughtError, appApiError, type AppApiResult } from "@/State/api/api";
import { selectSourceViewById } from "@/State/scoped/backups/sources/selectors";
import type { RootState } from "@/State/store/store";
import { emptyCursor, parseOperationsResponse } from "@/State/scoped/backups/sources/history/helpers";
import type { HistoryCursor } from "@/State/scoped/backups/sources/history/types";
import { getUnixTimeRange } from "./unixTimeRange";

type SourceArg = {
	sourceId: string;
};

type SourcePeriodArg = {
	sourceId: string;
	period: Period;
	offset: number;
};

type SourcePageArg = {
	sourceId: string;
	skip: number;
	take: number;
};

type EarningsOpsArg = {
	sourceId: string;
	period: Period;
	offset: number;
	appId: string;
};

type EarningsOpsPage = {
	operations: UserOperation[];
	hasMore: boolean;
};

type EarningsOpsPageParam = {
	beforeId?: string;
	toUnix?: number;
};

type UserOpsArg = {
	sourceId: string;
	userId: string;
};

type UserOpsPage = {
	operations: UserOperation[];
	hasMore: boolean;
	cursor: HistoryCursor;
};

type AddPeerArg = SourceArg & {
	pubkey: string;
	host: string;
	port: number;
};

type OpenChannelArg = SourceArg & {
	node_pubkey: string;
	local_funding_amount: number;
	sat_per_v_byte: number;
};

type InvoiceSwapQuotesArg = SourceArg & {
	amountSats: number;
};

type PayInvoiceSwapArg = SourceArg & {
	swap_operation_id: string;
	sat_per_v_byte: number;
};

type RefundInvoiceSwapArg = SourceArg & {
	swap_operation_id: string;
	sat_per_v_byte: number;
};

type TxSwapQuotesArg = SourceArg & {
	amountSats: number;
};

type PayTxSwapArg = SourceArg & {
	swap_operation_id: string;
	address: string;
};

type BumpTxArg = SourceArg & {
	txid: string;
	output_index: number;
	sat_per_vbyte: number;
};

type FetchAssetsArg = SourceArg & AssetsAndLiabilitiesReqV2;

type UpdateAdminNodeSettingsArg = SourceArg & UpdateAdminNodeSettingsRequest;

type UpdateChannelPolicyArg = SourceArg & {
	channel_point: string;
	policy: ChannelPolicy;
};

type CloseChannelArg = SourceArg & {
	funding_txid: string;
	output_index: number;
	force: boolean;
	sat_per_v_byte: number;
};

function isAlreadyConnected(reason: string) {
	const r = reason.toLowerCase();
	return r.includes("already connected") || r.includes("already exists");
}

async function clientForSource(getState: () => unknown, sourceId: string) {
	const source = selectSourceViewById(getState() as RootState, sourceId);
	if (!source) throw new Error("Source is not available");
	return getNostrClient(
		{ pubkey: source.lpk, relays: source.relays },
		source.keys,
	);
}

export const pubDashApi = appApi.injectEndpoints({
	endpoints: (b) => ({
		getLndInfo: b.query<LndGetInfoResponse, SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "LndInfo", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<LndGetInfoResponse>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.LndGetInfo({ nodeId: 0 });
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch service status");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch service status");
				}
			},
		}),
		getAppsMetrics: b.query<AppsMetrics, SourcePeriodArg>({
			providesTags: (_result, _error, { sourceId, period, offset }) => [
				{ type: "AppsMetrics", id: `${sourceId}:${period}:${offset}` },
			],
			queryFn: async ({ sourceId, period, offset }, api): Promise<AppApiResult<AppsMetrics>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const periodRange = getUnixTimeRange(period, offset);
					const res = await client.GetAppsMetrics({
						include_operations: false,
						bounded: true,
						...periodRange,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "App metrics failed");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "App metrics failed");
				}
			},
		}),
		getLndMetrics: b.query<LndMetrics, SourcePeriodArg>({
			providesTags: (_result, _error, { sourceId, period, offset }) => [
				{ type: "LndMetrics", id: `${sourceId}:${period}:${offset}` },
			],
			queryFn: async ({ sourceId, period, offset }, api): Promise<AppApiResult<LndMetrics>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const periodRange = getUnixTimeRange(period, offset);
					const res = await client.GetLndMetrics({
						...periodRange,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Lnd metrics failed");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Lnd metrics failed");
				}
			},
		}),
		getLndForwardingMetrics: b.query<LndForwardingMetrics, SourcePeriodArg>({
			providesTags: (_result, _error, { sourceId, period, offset }) => [
				{ type: "LndForwarding", id: `${sourceId}:${period}:${offset}` },
			],
			queryFn: async ({ sourceId, period, offset }, api): Promise<AppApiResult<LndForwardingMetrics>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const periodRange = getUnixTimeRange(period, offset);
					const res = await client.GetLndForwardingMetrics({
						...periodRange,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch forwarding metrics");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch forwarding metrics");
				}
			},
		}),
		listChannels: b.query<OpenChannel[], SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "OpenChannels", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<OpenChannel[]>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.ListChannels();
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to list channels");
					}
					return { data: res.open_channels };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to list channels");
				}
			},
		}),
		listPeers: b.query<LndPeer[], SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "LndPeers", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<LndPeer[]>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.ListPeers();
					if (res.status !== "OK") {
						return appApiError(res.reason || "Could not list peers");
					}
					return { data: res.peers };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Could not list peers");
				}
			},
		}),
		addPeer: b.mutation<void, AddPeerArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "LndPeers", id: sourceId },
			],
			queryFn: async ({ sourceId, pubkey, host, port }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.AddPeer({ pubkey, host, port });
					if (res.status !== "OK" && !isAlreadyConnected(res.reason)) {
						return appApiError(res.reason || "Could not connect peer");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Could not connect peer");
				}
			},
		}),
		updateChannelPolicy: b.mutation<void, UpdateChannelPolicyArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "OpenChannels", id: sourceId },
			],
			queryFn: async ({ sourceId, channel_point, policy }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.UpdateChannelPolicy({
						policy,
						update: {
							type: UpdateChannelPolicyRequest_update_type.CHANNEL_POINT,
							channel_point,
						},
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Could not update policy");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Could not update policy");
				}
			},
		}),
		closeChannel: b.mutation<void, CloseChannelArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "OpenChannels", id: sourceId },
			],
			queryFn: async ({ sourceId, funding_txid, output_index, force, sat_per_v_byte }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.CloseChannel({
						funding_txid,
						output_index,
						force,
						sat_per_v_byte,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Could not close channel");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Could not close channel");
				}
			},
		}),
		openChannel: b.mutation<void, OpenChannelArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "OpenChannels", id: sourceId },
				{ type: "LndPeers", id: sourceId },
			],
			queryFn: async ({ sourceId, node_pubkey, local_funding_amount, sat_per_v_byte }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.OpenChannel({
						node_pubkey,
						local_funding_amount,
						sat_per_v_byte,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Could not open channel");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Could not open channel");
				}
			},
		}),
		listAdminInvoiceSwaps: b.query<InvoiceSwapsList, SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "InvoiceSwaps", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<InvoiceSwapsList>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.ListAdminInvoiceSwaps();
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch swaps");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch swaps");
				}
			},
		}),
		getAdminInvoiceSwapQuotes: b.mutation<InvoiceSwapQuoteList, InvoiceSwapQuotesArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "InvoiceSwaps", id: sourceId },
			],
			queryFn: async ({ sourceId, amountSats }, api): Promise<AppApiResult<InvoiceSwapQuoteList>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetAdminInvoiceSwapQuotes({ amount_sats: amountSats });
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch quotes");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch quotes");
				}
			},
		}),
		payAdminInvoiceSwap: b.mutation<void, PayInvoiceSwapArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "InvoiceSwaps", id: sourceId },
			],
			queryFn: async ({ sourceId, swap_operation_id, sat_per_v_byte }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.PayAdminInvoiceSwap({
						sat_per_v_byte,
						swap_operation_id,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to pay swap");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to pay swap");
				}
			},
		}),
		refundAdminInvoiceSwap: b.mutation<void, RefundInvoiceSwapArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "InvoiceSwaps", id: sourceId },
			],
			queryFn: async ({ sourceId, swap_operation_id, sat_per_v_byte }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.RefundAdminInvoiceSwap({
						sat_per_v_byte,
						swap_operation_id,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to refund swap");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to refund swap");
				}
			},
		}),
		listAdminTxSwaps: b.query<TxSwapsList, SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "TxSwaps", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<TxSwapsList>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.ListAdminTxSwaps();
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch swaps");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch swaps");
				}
			},
		}),
		getAdminTransactionSwapQuotes: b.mutation<TransactionSwapQuoteList, TxSwapQuotesArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "TxSwaps", id: sourceId },
			],
			queryFn: async ({ sourceId, amountSats }, api): Promise<AppApiResult<TransactionSwapQuoteList>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetAdminTransactionSwapQuotes({
						transaction_amount_sats: amountSats,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch quotes");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch quotes");
				}
			},
		}),
		payAdminTransactionSwap: b.mutation<void, PayTxSwapArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "TxSwaps", id: sourceId },
			],
			queryFn: async ({ sourceId, swap_operation_id, address }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.PayAdminTransactionSwap({
						address,
						swap_operation_id,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to pay swap");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to pay swap");
				}
			},
		}),
		bumpTx: b.mutation<void, BumpTxArg>({
			queryFn: async ({ sourceId, txid, output_index, sat_per_vbyte }, api): Promise<AppApiResult<void>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.BumpTx({ txid, output_index, sat_per_vbyte });
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to bump tx");
					}
					return { data: undefined };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to bump tx");
				}
			},
		}),
		getUsersAdminInfo: b.query<UsersAdminInfo, SourcePageArg>({
			providesTags: (_result, _error, { sourceId, skip, take }) => [
				{ type: "UsersAdmin", id: `${sourceId}:${skip}:${take}` },
			],
			queryFn: async ({ sourceId, skip, take }, api): Promise<AppApiResult<UsersAdminInfo>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetUsersAdminInfo({ skip, take });
					if (res.status !== "OK") {
						return appApiError(res.reason || "Could not list users");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Could not list users");
				}
			},
		}),
		getUserOperationsFromAdmin: b.infiniteQuery<UserOpsPage, UserOpsArg, HistoryCursor>({
			providesTags: (_result, _error, { sourceId, userId }) => [
				{ type: "UserOperations", id: `${sourceId}:${userId}` },
			],
			infiniteQueryOptions: {
				initialPageParam: emptyCursor(),
				getNextPageParam: (lastPage): HistoryCursor | undefined => {
					if (!lastPage.hasMore) return undefined;
					return lastPage.cursor;
				},
			},
			queryFn: async ({ queryArg, pageParam }, api): Promise<AppApiResult<UserOpsPage>> => {
				const { sourceId, userId } = queryArg;
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetUserOperationsFromAdmin({
						...pageParam,
						user_id: userId,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch operations");
					}
					const { operations, newCursor, needMoreData } = parseOperationsResponse(res, pageParam);
					return {
						data: {
							operations,
							hasMore: needMoreData,
							cursor: newCursor,
						},
					};
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch operations");
				}
			},
		}),
		getEarningsOps: b.infiniteQuery<EarningsOpsPage, EarningsOpsArg, EarningsOpsPageParam>({
			infiniteQueryOptions: {
				initialPageParam: {},
				getNextPageParam: (lastPage): EarningsOpsPageParam | undefined => {
					if (!lastPage.hasMore) return undefined;
					const last = lastPage.operations[lastPage.operations.length - 1];
					if (!last?.operationId || last.paidAtUnix <= 0) return undefined;
					return { beforeId: last.operationId, toUnix: last.paidAtUnix };
				},
			},
			queryFn: async ({ queryArg, pageParam }, api): Promise<AppApiResult<EarningsOpsPage>> => {
				const { sourceId, period, offset, appId } = queryArg;
				try {
					const client = await clientForSource(api.getState, sourceId);
					const periodRange = getUnixTimeRange(period, offset);
					const res = await client.GetAppsMetrics({
						include_operations: true,
						bounded: true,
						...(pageParam.beforeId && pageParam.toUnix != null
							? {
								from_unix: periodRange?.from_unix,
								to_unix: pageParam.toUnix,
								operations_app_id: appId,
								operations_before_id: pageParam.beforeId,
							}
							: {
								...periodRange,
								operations_app_id: appId,
							}),
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to load more operations");
					}
					const app = res.apps.find((a) => a.app.id === appId);
					if (!app) return appApiError("Failed to load more operations");
					return {
						data: {
							operations: app.operations,
							hasMore: app.operations_has_more ?? false,
						},
					};
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to load more operations");
				}
			},
		}),
		getAssetsAndLiabilities: b.query<AssetsAndLiabilitiesV2, SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "AssetsLiabilities", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<AssetsAndLiabilitiesV2>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetAssetsAndLiabilitiesV2({
						lnd_providers: [],
						liquidity_providers: [],
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch assets");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch assets");
				}
			},
		}),
		listUtxos: b.query<LndUtxo[], SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "LndUtxos", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<LndUtxo[]>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.ListUtxos();
					if (res.status !== "OK") {
						return appApiError(res.reason || "Could not list UTXOs");
					}
					return { data: res.utxos };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Could not list UTXOs");
				}
			},
		}),
		fetchAssetsAndLiabilities: b.mutation<AssetsAndLiabilitiesV2, FetchAssetsArg>({
			queryFn: async ({ sourceId, lnd_providers, liquidity_providers }, api): Promise<AppApiResult<AssetsAndLiabilitiesV2>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetAssetsAndLiabilitiesV2({
						lnd_providers,
						liquidity_providers,
					});
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch assets");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch assets");
				}
			},
		}),
		getAdminNodeSettings: b.query<AdminNodeSettings, SourceArg>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "AdminNodeSettings", id: sourceId },
			],
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<AdminNodeSettings>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetAdminNodeSettings();
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to load settings");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to load settings");
				}
			},
		}),
		updateAdminNodeSettings: b.mutation<AdminNodeSettings, UpdateAdminNodeSettingsArg>({
			invalidatesTags: (_result, _error, { sourceId }) => [
				{ type: "AdminNodeSettings", id: sourceId },
			],
			queryFn: async ({ sourceId, ...req }, api): Promise<AppApiResult<AdminNodeSettings>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.UpdateAdminNodeSettings(req);
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to save settings");
					}
					return { data: res };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to save settings");
				}
			},
		}),
		getSeed: b.mutation<string[], SourceArg>({
			queryFn: async ({ sourceId }, api): Promise<AppApiResult<string[]>> => {
				try {
					const client = await clientForSource(api.getState, sourceId);
					const res = await client.GetSeed();
					if (res.status !== "OK") {
						return appApiError(res.reason || "Failed to fetch seed");
					}
					return { data: res.seed };
				} catch (e: unknown) {
					return appApiCaughtError(e, "Failed to fetch seed");
				}
			},
		}),
	}),
});

export const {
	useGetLndInfoQuery,
	useGetAppsMetricsQuery,
	useGetLndMetricsQuery,
	useGetLndForwardingMetricsQuery,
	useListChannelsQuery,
	useListPeersQuery,
	useAddPeerMutation,
	useOpenChannelMutation,
	useUpdateChannelPolicyMutation,
	useCloseChannelMutation,
	useGetUsersAdminInfoQuery,
	useGetUserOperationsFromAdminInfiniteQuery,
	useGetEarningsOpsInfiniteQuery,
	useListAdminInvoiceSwapsQuery,
	useGetAdminInvoiceSwapQuotesMutation,
	usePayAdminInvoiceSwapMutation,
	useRefundAdminInvoiceSwapMutation,
	useListAdminTxSwapsQuery,
	useGetAdminTransactionSwapQuotesMutation,
	usePayAdminTransactionSwapMutation,
	useBumpTxMutation,
	useGetAssetsAndLiabilitiesQuery,
	useListUtxosQuery,
	useFetchAssetsAndLiabilitiesMutation,
	useGetAdminNodeSettingsQuery,
	useUpdateAdminNodeSettingsMutation,
	useGetSeedMutation,
} = pubDashApi;
