import { useCallback, useEffect, useMemo, useState } from "react";
import { RouteComponentProps } from "react-router-dom";
import {
    IonBadge,
    IonButton,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonText,
    useIonLoading,
    useIonRouter,
} from "@ionic/react";
import { toast } from "react-toastify";
import { UserAdminInfo, UserOperation } from "@/Api/pub/autogenerated/ts/types";
import { DashboardShell } from "@/Layout2/Metrics/DashboardShell";
import { DashErrorBanner } from "./DashErrorBanner";
import { useAppSelector } from "@/State/store/hooks";
import { selectAdminSourceViews } from "@/State/scoped/backups/sources/selectors";
import { selectSelectedMetricsAdminSourceId } from "@/State/runtime/slice";
import { emptyCursor, parseOperationsResponse } from "@/State/scoped/backups/sources/history/helpers";
import type { HistoryCursor } from "@/State/scoped/backups/sources/history/types";
import { AdminOperationsList } from "./adminOperationDisplay";
import { fetcher } from "./fetcher";
import { formatTableAmount } from "./metricsDataTable";
import { PubUpgradeNotice } from "./PubUpgradeNotice";
import { MetricsProbeSkeleton } from "./MetricsProbeSkeleton";
import { isMissingDashboardRpcError } from "./pubDashboardCapability";
import { usePubDashboardCapability } from "./usePubDashboardCapability";

type LocationState = { user?: UserAdminInfo };

function formatSats(n: number): string {
    return formatTableAmount(n) + " sats";
}

function trimId(id: string): string {
    return id.length <= 12 ? id : `${id.slice(0, 6)}…${id.slice(-4)}`;
}

export default function UserOperationsAdmin({ match, location, history }: RouteComponentProps) {
    const router = useIonRouter();
    const { userId } = match.params as { userId: string };
    const userFromState = (location.state as LocationState | undefined)?.user;

    const admins = useAppSelector(selectAdminSourceViews);
    const selectedId = useAppSelector(selectSelectedMetricsAdminSourceId);
    const adminSource = useMemo(
        () => admins.find((a) => a.sourceId === selectedId),
        [admins, selectedId]
    );
    const {
        needsUpgrade,
        checking: checkingPubCapability,
        recheck,
        markNeedsUpgrade,
    } = usePubDashboardCapability(adminSource);

    const [operations, setOperations] = useState<UserOperation[]>([]);
    const [cursor, setCursor] = useState<HistoryCursor>(emptyCursor);
    const [hasMore, setHasMore] = useState(false);
    const [loading, setLoading] = useState(true);
    const [loadingMore, setLoadingMore] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [presentLoading, dismissLoading] = useIonLoading();

    const fetchOperations = useCallback(async (nextCursor: HistoryCursor, append: boolean) => {
        if (!adminSource) return;

        const res = await fetcher(
            { pubkey: adminSource.lpk, relays: adminSource.relays },
            adminSource.keys,
            {
                onStart: async () => {
                    setError(null);
                    if (append) {
                        setLoadingMore(true);
                    } else {
                        setLoading(true);
                        await dismissLoading();
                        await presentLoading({ message: "Fetching operations...", cssClass: "app-loading" });
                    }
                },
                onEnd: async () => {
                    if (append) {
                        setLoadingMore(false);
                    } else {
                        setLoading(false);
                        await dismissLoading();
                    }
                },
                onFail: (err) => {
                    if (isMissingDashboardRpcError(err)) {
                        markNeedsUpgrade();
                        return;
                    }
                    setError(err);
                    toast.error(err);
                },
            },
            [(client) => client.GetUserOperationsFromAdmin({ ...nextCursor, user_id: userId })]
        );

        if (!res) return;

        const { operations: batch, newCursor, needMoreData } = parseOperationsResponse(res[0], nextCursor);
        setOperations((prev) => (append ? [...prev, ...batch] : batch));
        setCursor(newCursor);
        setHasMore(needMoreData);
    }, [adminSource, dismissLoading, markNeedsUpgrade, presentLoading, userId]);

    useEffect(() => {
        if (checkingPubCapability) return;
        if (needsUpgrade) {
            setLoading(false);
            return;
        }
        setOperations([]);
        setCursor(emptyCursor());
        setHasMore(false);
        void fetchOperations(emptyCursor(), false);
    }, [checkingPubCapability, fetchOperations, needsUpgrade, userId]);

    const loadMore = () => {
        if (loadingMore || !hasMore || needsUpgrade) return;
        void fetchOperations(cursor, true);
    };

    return (
        <DashboardShell title={`User ${trimId(userId)}`} backHref="/metrics/users">
                {needsUpgrade && (
                    <PubUpgradeNotice
                        featureLabel="Users admin"
                        onRecheck={recheck}
                        checking={checkingPubCapability}
                    />
                )}

                {!needsUpgrade && checkingPubCapability && (
                    <MetricsProbeSkeleton variant="page" />
                )}

                {!needsUpgrade && !checkingPubCapability && error && (
                    <DashErrorBanner
                        message={error}
                        onRetry={() => void fetchOperations(emptyCursor(), false)}
                        onChangeSource={() => router.push("/metrics/select", "back")}
                    />
                )}

                {!needsUpgrade && !checkingPubCapability && !error && (
                    <>
                        <IonCard>
                            <IonCardHeader>
                                <IonCardTitle>{trimId(userId)}</IonCardTitle>
                            </IonCardHeader>
                            <IonCardContent>
                                {userFromState ? (
                                    <div
                                        style={{
                                            padding: "12px",
                                            background: "var(--ion-color-light)",
                                            borderRadius: "8px",
                                            display: "flex",
                                            flexDirection: "column",
                                            gap: 8,
                                        }}
                                    >
                                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                                            <IonText color="medium">Balance</IonText>
                                            <IonText><strong>{formatSats(userFromState.balance)}</strong></IonText>
                                        </div>
                                        {userFromState.locked && (
                                            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                                                <IonText color="medium">Status</IonText>
                                                <IonBadge color="danger">Locked</IonBadge>
                                            </div>
                                        )}
                                        {userFromState.owner_of_app_id && (
                                            <div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}>
                                                <IonText color="medium">App owner</IonText>
                                                <IonText style={{ textAlign: "right" }}>{trimId(userFromState.owner_of_app_id)}</IonText>
                                            </div>
                                        )}
                                        {userFromState.app_users.length > 0 && (
                                            <div style={{ display: "flex", justifyContent: "space-between" }}>
                                                <IonText color="medium">Linked app users</IonText>
                                                <IonText>{userFromState.app_users.length}</IonText>
                                            </div>
                                        )}
                                    </div>
                                ) : (
                                    <IonText color="medium">User summary unavailable — open from the users list for details.</IonText>
                                )}
                            </IonCardContent>
                        </IonCard>

                        <IonCard className="ion-margin-top">
                            <IonCardHeader>
                                <IonCardTitle>
                                    Operations
                                    {operations.length > 0 && (
                                        <IonText color="medium" style={{ fontSize: "0.85rem", fontWeight: 400, marginLeft: "8px" }}>
                                            ({operations.length})
                                        </IonText>
                                    )}
                                </IonCardTitle>
                            </IonCardHeader>
                            <IonCardContent>
                                {!loading && operations.length > 0 && (
                                    <IonText color="medium" style={{ fontSize: "0.8rem", display: "block", marginBottom: "12px" }}>
                                        {operations.length} operation{operations.length === 1 ? "" : "s"} loaded
                                    </IonText>
                                )}

                                {!loading && <AdminOperationsList operations={operations} />}

                                {hasMore && (
                                    <IonButton
                                        expand="block"
                                        fill="outline"
                                        className="ion-margin-top"
                                        disabled={loadingMore}
                                        onClick={loadMore}
                                    >
                                        {loadingMore ? "Loading..." : "Load more operations"}
                                    </IonButton>
                                )}
                            </IonCardContent>
                        </IonCard>
                    </>
                )}
        </DashboardShell>
    );
}

