import { useMemo } from "react";
import { RouteComponentProps } from "react-router-dom";
import {
	IonButton,
	IonCard,
	IonCardContent,
	IonCardHeader,
	IonCardTitle,
	IonSkeletonText,
	IonText,
} from "@ionic/react";
import { Period } from "@/Components/Dropdowns/LVDropdown";
import { UserAdminInfo } from "@/Api/pub/autogenerated/ts/types";
import { DashBoardPageChrome } from "@/Layout2/Metrics/DashBoardPageChrome";
import { DashErrorBanner } from "./DashErrorBanner";
import type { AppApiError } from "@/State/api/api";
import { useDashboardSource } from "./DashboardSourceContext";
import { AdminOperationsList } from "./adminOperationDisplay";
import { formatTableAmount, formatTableTs } from "./metricsDataTable";
import { PubUpgradeNotice } from "./PubUpgradeNotice";
import { useGetAppsMetricsQuery, useGetUserOperationsFromAdminInfiniteQuery } from "./pubDashApi";
import { useGetPubDashboardCapabilityQuery } from "./pubDashboardCapabilityApi";
import { appNamesById, isNodeAdmin, trimUserId, UserAppChips, userAppLabels } from "./userAdminDisplay";

type LocationState = { user?: UserAdminInfo };

function formatSats(n: number): string {
	return formatTableAmount(n) + " sats";
}

export default function UserOperationsAdmin({ match, location }: RouteComponentProps) {
	const { userId } = match.params as { userId: string };
	const userFromState = (location.state as LocationState | undefined)?.user;
	const source = useDashboardSource();
	const sourceId = source.sourceId;
	const adminNpub = source.keys.publicKey;
	const cap = useGetPubDashboardCapabilityQuery({ sourceId });
	const needsUpgrade = cap.data === "needs_upgrade";
	const capPending = !cap.data && (cap.isFetching || !cap.error);
	const {
		data,
		error,
		fetchNextPage,
		hasNextPage,
		isFetching,
		isFetchingNextPage,
		refetch,
	} = useGetUserOperationsFromAdminInfiniteQuery(
		{ sourceId, userId },
		{ skip: needsUpgrade || capPending },
	);
	const apps = useGetAppsMetricsQuery(
		{ sourceId, period: Period.ALL_TIME, offset: 0 },
		{ skip: needsUpgrade || capPending },
	);
	const names = useMemo(
		() => appNamesById(apps.data?.apps.map((row) => row.app) ?? []),
		[apps.data],
	);
	const operations = data?.pages.flatMap((page) => page.operations) ?? [];
	const loading = !data && (isFetching || !error);

	return (
		<DashBoardPageChrome title={`User ${trimUserId(userId)}`} backHref="/dashboard/users">
			{needsUpgrade ? (
				<PubUpgradeNotice
					featureLabel="Users admin"
					onRecheck={() => void cap.refetch()}
					checking={cap.isFetching}
				/>
			) : capPending || loading ? (
				<UserOpsSkeleton />
			) : !data ? (
				<DashErrorBanner
					message={(error as AppApiError | undefined)?.message || "Failed to fetch operations"}
					onRetry={() => void refetch()}
				/>
			) : (
				<>
					<IonCard>
						<IonCardHeader>
							<IonCardTitle>{trimUserId(userId)}</IonCardTitle>
						</IonCardHeader>
						<IonCardContent>
							{userFromState ? (
								<UserSummary user={userFromState} names={names} admin={isNodeAdmin(userFromState, adminNpub)} />
							) : (
								<IonText color="medium">User summary unavailable — open from the users list for details.</IonText>
							)}
						</IonCardContent>
					</IonCard>

					<IonCard className="ion-margin-top">
						<IonCardHeader>
							<IonCardTitle>
								Operations
								{operations.length > 0 && (
									<IonText color="medium" style={{ fontSize: "0.85rem", fontWeight: 400, marginLeft: "8px" }}>
										({operations.length})
									</IonText>
								)}
							</IonCardTitle>
						</IonCardHeader>
						<IonCardContent>
							{operations.length > 0 && (
								<IonText color="medium" style={{ fontSize: "0.8rem", display: "block", marginBottom: "12px" }}>
									{operations.length} operation{operations.length === 1 ? "" : "s"} loaded
								</IonText>
							)}

							<AdminOperationsList operations={operations} />

							{hasNextPage && (
								<IonButton
									expand="block"
									fill="outline"
									className="ion-margin-top"
									disabled={isFetchingNextPage}
									onClick={() => void fetchNextPage()}
								>
									{isFetchingNextPage ? "Loading..." : "Load more operations"}
								</IonButton>
							)}
						</IonCardContent>
					</IonCard>
				</>
			)}
		</DashBoardPageChrome>
	);
}

function UserSummary({ user, names, admin }: { user: UserAdminInfo; names: Map<string, string>; admin: boolean }) {
	const labels = userAppLabels(user, names);
	return (
		<div
			style={{
				padding: "12px",
				background: "var(--ion-color-light)",
				borderRadius: "8px",
				display: "flex",
				flexDirection: "column",
				gap: 8,
			}}
		>
			<div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>
				<IonText color="medium">Balance</IonText>
				<IonText><strong>{formatSats(user.balance)}</strong></IonText>
			</div>
			{(labels.length > 0 || admin) && (
				<div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}>
					<IonText color="medium">App</IonText>
					<UserAppChips labels={labels} admin={admin} />
				</div>
			)}
			{user.locked && (
				<div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
					<IonText color="medium">Account</IonText>
					<span className="dash-chip is-locked">Locked</span>
				</div>
			)}
			{typeof user.last_seen_at_unix === "number" && (
				<div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>
					<IonText color="medium">Last seen</IonText>
					<IonText>{formatTableTs(user.last_seen_at_unix)}</IonText>
				</div>
			)}
		</div>
	);
}

function UserOpsSkeleton() {
	return (
		<>
			<IonCard>
				<IonCardHeader>
					<IonCardTitle>
						<IonSkeletonText animated style={{ width: "36%", height: 16, margin: 0 }} />
					</IonCardTitle>
				</IonCardHeader>
				<IonCardContent>
					<IonSkeletonText animated style={{ width: "100%", height: 72, margin: 0 }} />
				</IonCardContent>
			</IonCard>
			<IonCard className="ion-margin-top">
				<IonCardHeader>
					<IonCardTitle>Operations</IonCardTitle>
				</IonCardHeader>
				<IonCardContent>
					<IonSkeletonText animated style={{ width: "100%", height: 36, margin: 0 }} />
					<IonSkeletonText animated style={{ width: "90%", height: 36, marginTop: 8 }} />
					<IonSkeletonText animated style={{ width: "70%", height: 36, marginTop: 8 }} />
				</IonCardContent>
			</IonCard>
		</>
	);
}
