import { useMemo } from "react";
import type { LndUtxo } from "@/Api/pub/autogenerated/ts/types";
import type { AppApiError } from "@/State/api/api";
import { formatTableAmount } from "./metricsDataTable";
import { useDashboardSource } from "./DashboardSourceContext";
import { useListUtxosQuery } from "./pubDashApi";
import { useGetPubDashboardCapabilityQuery } from "./pubDashboardCapabilityApi";
import { PubUpgradeNotice } from "./PubUpgradeNotice";

export function UtxoList() {
	const { sourceId } = useDashboardSource();
	const cap = useGetPubDashboardCapabilityQuery({ sourceId });
	const needsUpgrade = cap.data === "needs_upgrade";
	const capPending = !cap.data && (cap.isFetching || !cap.error);
	const { data, error, isFetching } = useListUtxosQuery(
		{ sourceId },
		{ skip: needsUpgrade || capPending },
	);
	const ordered = useMemo(() => sortUtxos(data ?? []), [data]);
	const loading = capPending || (!data && (isFetching || !error));
	const errMsg = (error as AppApiError | undefined)?.message || "Could not list UTXOs";

	if (needsUpgrade) {
		return (
			<PubUpgradeNotice
				featureLabel="listing on-chain coins"
				onRecheck={cap.refetch}
				checking={cap.isFetching}
			/>
		);
	}

	return (
		<div className="dash-section">
			<div className="dash-section-head">
				<h2>On-chain</h2>
				<span className="dash-section-count">{loading ? "…" : ordered.length}</span>
			</div>
			{error ? <p className="dash-field-hint">{errMsg}</p> : null}
			{loading ? (
				<p className="dash-field-hint">Loading UTXOs…</p>
			) : ordered.length === 0 ? (
				<p className="dash-field-hint">No unspent outputs.</p>
			) : (
				<div className="dash-peer-stack">
					{ordered.map((utxo) => (
						<UtxoRow key={outpoint(utxo)} utxo={utxo} />
					))}
				</div>
			)}
		</div>
	);
}

function UtxoRow({ utxo }: { utxo: LndUtxo }) {
	const unconfirmed = utxo.confirmations <= 0;
	return (
		<div className="dash-peer-item">
			<div className="dash-peer-item-main">
				<div className="dash-peer-item-name">{formatTableAmount(utxo.amount_sat)} sats</div>
				<div className="dash-peer-item-sub">
					{shortId(utxo.address)} · {shortId(utxo.txid)}:{utxo.output_index}
					{unconfirmed ? "" : ` · ${utxo.confirmations} conf`}
				</div>
			</div>
			{unconfirmed && <span className="dash-pill is-warn">unconfirmed</span>}
		</div>
	);
}

function sortUtxos(utxos: LndUtxo[]) {
	return [...utxos].sort((a, b) => {
		if (a.confirmations <= 0 && b.confirmations > 0) return -1;
		if (a.confirmations > 0 && b.confirmations <= 0) return 1;
		return b.amount_sat - a.amount_sat;
	});
}

function outpoint(utxo: LndUtxo) {
	return `${utxo.txid}:${utxo.output_index}`;
}

function shortId(value: string) {
	if (value.length < 16) return value || "—";
	return `${value.slice(0, 8)}…${value.slice(-8)}`;
}
