import { IonChip, IonCol, IonGrid, IonItem, IonLabel, IonRow, IonText } from "@ionic/react";
import { formatSatoshi } from "@/lib/units";
import { OfferInvoice } from "@/Api/pub/autogenerated/ts/types";
import { parseInvoiceInput } from "@/lib/parse";
import { useMemo } from "react";
import moment from "moment";


interface OfferInvoiceItemProps {
	invoice: OfferInvoice
}

const OfferInvoiceItem = ({ invoice }: OfferInvoiceItemProps) => {
	const isPaid = invoice.amount > 0;

	// useMemo to catch thrown errors
	const parsedInvoice = useMemo(() => {
		try {
			return parseInvoiceInput(invoice.invoice);
		} catch {
			return null;
		}
	}, [invoice])


	if (parsedInvoice === null) {
		return null;
	}

	return (
		<IonItem lines="inset">
			<IonLabel>
				<IonGrid>
					<IonRow className="ion-nowrap ion-justify-content-between ion-align-items-center">
						<IonCol size="auto" className="ion-text-start">
							<IonText className="text-medium"><IonText color="primary">{formatSatoshi(parsedInvoice.amount)}</IonText> sats</IonText>
						</IonCol>
						<IonCol size="auto" className="ion-text-end">
							<IonChip color="primary">{isPaid ? 'Paid Invoice' : 'Unpaid Invoice'}</IonChip>
						</IonCol>
					</IonRow>
					{
						isPaid
						&&
						<IonRow className="ion-margin-top ion-nowrap">
							<IonCol size="6">
								{
									(Object.values(invoice.data).some(v => v?.trim?.() !== "")) && (
										Object.entries(invoice.data).map(([key, value]) => (
											value?.trim?.() ? (
												<IonRow key={key}>
													<IonCol>
														<IonText className="text-quiet">{key}</IonText><IonText className="text-medium">: {value}</IonText>
													</IonCol>
												</IonRow>
											) : null
										))
									)
								}
							</IonCol>
							<IonCol size="6" className="ion-text-end">
								<IonText className="text-quiet text-sm">Paid {moment(invoice.paid_at_unix * 1000).fromNow()}</IonText>
							</IonCol>
						</IonRow>
					}
				</IonGrid>
			</IonLabel>
		</IonItem>
	);
}

export default OfferInvoiceItem;
