import { createSelector } from "@reduxjs/toolkit";
import { docsSelectors, metadataSelectors } from "./slice";
import { NostrKeyPair } from "@/lib/regex";
import { Satoshi } from "@/lib/types/units";
import { SourceDocV0 } from "./schema";
import { SourceMetadata } from "./metadata/types";
import { selectFavoriteSourceId } from "@/State/scoped/backups/identity/slice";
import { RootState } from "@/State/store/store";
import { selectBeaconJoinState, joinSourceBeacon, type BeaconHealth } from "@/State/scoped/beacons/selectors";
import { canonicalRelayUrls } from "@/State/scoped/beacons/relays";
import type { CumulativeFees } from "@/Api/pub/autogenerated/ts/types";

export type { BeaconHealth };
export { computeBeaconHealth } from "@/State/scoped/beacons/selectors";

export const selectLiveSourceIds = createSelector(
	[docsSelectors.selectAll],
	(entities) => entities
		.map(e => e.draft)
		.filter(d => !(d.deleted?.value))
		.map(d => d.source_id)
);


export const selectLiveSourceEntities = createSelector(
	[docsSelectors.selectAll],
	(entities) => entities.filter(e => !isDeleted(e.draft))
);



export type SourceView = {
	sourceId: string;
	label: string | null;
	relays: string[];
	beaconStale: BeaconHealth;
	beaconLastSeenAtMs: number
	beaconName?: string;
	beaconAvatarUrl?: string;
	beaconFees?: CumulativeFees;
	beaconNextRelay?: string;
	balanceSats: Satoshi;
	maxWithdrawableSats: Satoshi;
	lpk: string;
	topicId?: string;
	keys: NostrKeyPair;
	bridgeUrl: string | null;
	isNDebitDiscoverable: boolean;
	adminToken: string | null;
	vanityName?: string;
	ndebit?: string;
	noffer?: string;
	nmanage?: string;
};

/** Fields needed to open a Pub client. Ignores beacon/balance churn. */
export type AdminRpcSource = Pick<SourceView, "sourceId" | "lpk" | "keys" | "relays">;

/** Stable across beacon-only updates so mounted pages do not repeat RPCs. */
export const sourceRpcKey = (source: AdminRpcSource) => JSON.stringify([
	source.sourceId,
	source.lpk,
	source.keys.publicKey,
	source.relays,
]);

const presentRelayUrls = (relays?: Record<string, { present: boolean }>) =>
	relays ? Object.keys(relays).filter(u => relays[u]?.present) : [];

const isDeleted = (d: SourceDocV0) => Boolean(d.deleted.value);

const joinDraftBeacon = (
	d: SourceDocV0,
	beacon: ReturnType<typeof selectBeaconJoinState>,
) => {
	const relays = canonicalRelayUrls(presentRelayUrls(d.relays));
	return {
		relays,
		joined: joinSourceBeacon({
			nowMs: beacon.nowMs,
			lpk: d.lpk,
			relays,
			node: beacon.nodes[d.lpk],
			lookups: beacon.lookups,
		}),
	};
};

export const selectSourceBeaconHealth = (state: RootState, sourceId: string): BeaconHealth | null => {
	const e = docsSelectors.selectById(state, sourceId);
	if (!e || e.draft.deleted.value) return null;
	return joinDraftBeacon(e.draft, selectBeaconJoinState(state)).joined.health;
};

const createSourceView = (
	d: SourceDocV0,
	m: SourceMetadata,
	beacon: ReturnType<typeof selectBeaconJoinState>,
): SourceView => {
	if (!m) {
		throw new Error("No metadata for source. Something went wrong");
	}

	const { relays, joined } = joinDraftBeacon(d, beacon);

	return {
		sourceId: d.source_id,
		label: d.label.value,
		lpk: d.lpk,
		topicId: m.topicId,
		keys: d.keys,
		relays,
		balanceSats: m.balance,
		maxWithdrawableSats: m.maxWithdrable,
		isNDebitDiscoverable: d.is_ndebit_discoverable.value,
		ndebit: m.ndebit,
		noffer: m.noffer,
		nmanage: m.nmanage,
		vanityName: m.vanityName,
		bridgeUrl: d.bridgeUrl.value,
		beaconStale: joined.health,
		beaconLastSeenAtMs: joined.lastSeenAtMs,
		beaconName: joined.name,
		beaconAvatarUrl: joined.avatarUrl,
		beaconFees: joined.fees,
		beaconNextRelay: joined.nextRelay,
		adminToken: d.admin_token.value
	};
}

export const selectSourceViews = createSelector(
	[
		docsSelectors.selectAll,
		metadataSelectors.selectEntities,
		selectBeaconJoinState,
	],
	(sourceEntities, metaEntities, beacon): SourceView[] => {
		const out: SourceView[] = [];
		for (const source of sourceEntities) {

			const d = source.draft;
			if (d.deleted.value) continue;

			out.push(createSourceView(d, metaEntities[d.source_id], beacon));
		}
		return out;
	}
);

export const selectSourceViewById = createSelector(
	[
		docsSelectors.selectEntities,
		metadataSelectors.selectEntities,
		selectBeaconJoinState,
		(_state: RootState, sourceId: string) => sourceId
	],
	(sourceEntities, metaEntities, beacon, sourceId) => {

		const e = sourceEntities[sourceId];
		if (!e || e.draft.deleted.value) return null;

		const d = e.draft;
		return createSourceView(d, metaEntities[d.source_id], beacon);
	}
)

export const selectSourceViewsByLpk = createSelector(
	[
		selectSourceViews,
		(_state: RootState, lpk: string) => lpk
	],
	(views, lpk) => views.filter(v => v.lpk === lpk)
);



export const selectHealthySourceViews = createSelector(
	[selectSourceViews],
	(views) => views.filter(v => v.beaconStale === "fresh")
);

export const selectAdminSourceViews = createSelector(
	[selectSourceViews],
	(views) => views.filter(v => !!v.adminToken)
);

/** Admin nodes for RPC. Docs only — does not change on beacon or balance ticks. */
export const selectAdminRpcSources = createSelector(
	[docsSelectors.selectAll],
	(sourceEntities): AdminRpcSource[] => {
		const out: AdminRpcSource[] = [];
		for (const source of sourceEntities) {
			const d = source.draft;
			if (d.deleted.value || !d.admin_token.value) continue;
			out.push({
				sourceId: d.source_id,
				lpk: d.lpk,
				keys: d.keys,
				relays: canonicalRelayUrls(presentRelayUrls(d.relays)),
			});
		}
		return out;
	},
);

export const selectSelectedAdminRpcSource = createSelector(
	[selectAdminRpcSources, (s: RootState) => s.runtime.selectedMetricsAdminSourceId],
	(sources, selectedId) => (
		selectedId ? sources.find(s => s.sourceId === selectedId) ?? null : null
	),
);


export const selectFavoriteSourceView = createSelector(
	[
		selectFavoriteSourceId,
		docsSelectors.selectEntities,
		metadataSelectors.selectEntities,
		selectBeaconJoinState,
	],
	(favId, sourceEntities, metaEntities, beacon): SourceView | null => {
		if (!favId) return null;
		const e = sourceEntities[favId];
		if (!e || e.draft.deleted.value) return null;

		const d = e.draft;
		return createSourceView(d, metaEntities[d.source_id], beacon)
	}
);


export const selectTotalBalance = createSelector(
	[metadataSelectors.selectAll, selectLiveSourceIds],
	(allMeta, liveIds) => {
		let total = 0;
		for (const meta of allMeta) {

			if (!liveIds.includes(meta.id)) continue; // ensure source is actually live (i.e. not marked deleted and awaiting publisher to actually delete)
			total += meta.balance;
		}
		return total as Satoshi;
	}
);
