import { useMemo } from 'react'
import * as Types from '../../Api/pub/autogenerated/ts/types'
export const ErrorsView = ({ errors }: { errors: Types.ErrorStats }) => {
    const rows = useMemo(() => {
        const { past10m, past1h, past1m, past24h, past6h } = errors
        const res: { s: string, v: number }[] = []
        res.push({ s: '24h', v: past24h.total > 0 ? Math.ceil(100 * past24h.errors / past24h.total) : 0 })
        res.push({ s: '6h', v: past6h.total > 0 ? Math.ceil(100 * past6h.errors / past6h.total) : 0 })
        res.push({ s: '1h', v: past1h.total > 0 ? Math.ceil(100 * past1h.errors / past1h.total) : 0 })
        res.push({ s: '10m', v: past10m.total > 0 ? Math.ceil(100 * past10m.errors / past10m.total) : 0 })
        res.push({ s: '1m', v: past1m.total > 0 ? Math.ceil(100 * past1m.errors / past1m.total) : 0 })
        return res.map(r => <div key={r.s} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <div>{r.s}</div>
            <div style={redBackground}>
                <div style={whiteBackground(r.v)}></div>
            </div>
            <div>{r.v}%</div>
        </div>)
    }, [errors])
    return <div style={{ display: 'flex', flexDirection: 'row', justifyContent: 'center' }}>
        {rows}
    </div>
}

const redBackground = { width: 50, height: 100, backgroundColor: 'red', margin: '0 5px' }
const whiteBackground = (percent: number) => ({ width: 50, height: 100 - percent, backgroundColor: 'white' })