import { useEffect, useMemo, useState } from "react"
import { Period } from "@/Components/Dropdowns/LVDropdown"
import { toast } from "react-toastify";
import * as Types from '../../../Api/pub/autogenerated/ts/types';
import { IonButton, IonContent, IonItem, IonPage, IonHeader, useIonLoading, useIonRouter, IonRow, IonText, IonInput, IonSegment, IonLabel, IonSegmentButton } from "@ionic/react";
import { flashOutline, linkOutline, personOutline } from "ionicons/icons";
import MetricsSubPageToolbar from "@/Layout2/Metrics/MetricsSubPageToolbar";
import { useAppSelector } from "@/State/store/hooks";
import { selectAdminNprofileViews } from "@/State/scoped/backups/sources/selectors";
import { selectSelectedMetricsAdminSourceId } from "@/State/runtime/slice";
import { TxSwapsList, TransactionSwapQuote } from "../../../Api/pub/autogenerated/ts/types";
import { fetcher, FetcherFuncs } from "../fetcher";
import AmountInput from "@/Components/AmountInput";
import TxSwaps from "./TxSwaps";
import SubmarineSwaps from "./SubmarineSwaps";

export default function AdminSwaps() {
    const [selectedView, setSelectedView] = useState("reverse");
    const admins = useAppSelector(selectAdminNprofileViews);
    const selectedId = useAppSelector(selectSelectedMetricsAdminSourceId);
    const adminSource = useMemo(
        () => admins.find(a => a.sourceId === selectedId),
        [admins, selectedId]
    );


    return <IonPage className="ion-page-width">
        <IonHeader className="ion-no-border">
            <MetricsSubPageToolbar title="Admin Swaps" />
        </IonHeader>
        <IonSegment value="rev" onIonChange={(e) => {
            setSelectedView(e.detail.value?.toString() || "");
        }}>
            <IonSegmentButton value="reverse">
                <IonLabel>Reverse Swaps</IonLabel>
            </IonSegmentButton>
            <IonSegmentButton value="submarine">
                <IonLabel>Submarine Swaps</IonLabel>
            </IonSegmentButton>
        </IonSegment>
        {selectedView === "reverse" && <TxSwaps adminSource={adminSource} />}
        {selectedView === "submarine" && <SubmarineSwaps adminSource={adminSource} />}
    </IonPage>;

}
