import { useMemo, useState } from "react"
import { toast } from "react-toastify";
import * as Types from '../../../Api/pub/autogenerated/ts/types';
import { IonButton, IonContent, IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonIcon, IonInput, IonItem, IonLabel, IonPage, IonHeader, IonSegment, IonSegmentButton, useIonLoading } from "@ionic/react";
import { flashOutline } from "ionicons/icons";
import MetricsSubPageToolbar from "@/Layout2/Metrics/MetricsSubPageToolbar";
import { useAppSelector } from "@/State/store/hooks";
import { NprofileView, selectAdminNprofileViews } from "@/State/scoped/backups/sources/selectors";
import { selectSelectedMetricsAdminSourceId } from "@/State/runtime/slice";
import { fetcher } from "../fetcher";
import TxSwaps from "./TxSwaps";
import SubmarineSwaps from "./SubmarineSwaps";

function BumpTxSection({ adminSource }: { adminSource: NprofileView | undefined }) {
    const [txid, setTxid] = useState("");
    const [outputIndex, setOutputIndex] = useState("");
    const [satPerVbyte, setSatPerVbyte] = useState("");
    const [presentLoading, dismissLoading] = useIonLoading();

    const bumpTx = async () => {
        if (!adminSource) return;
        const outIdx = parseInt(outputIndex, 10);
        const sats = parseFloat(satPerVbyte);
        if (!txid.trim() || isNaN(outIdx) || outIdx < 0 || isNaN(sats) || sats <= 0) {
            toast.error("Enter valid txid, output index (≥0), and sat/vB (>0)");
            return;
        }
        const req: Types.BumpTx = { txid: txid.trim(), output_index: outIdx, sat_per_vbyte: sats };
        const res = await fetcher(
            { pubkey: adminSource.lpk, relays: adminSource.relays },
            adminSource.keys,
            {
                onStart: async () => { await dismissLoading(); await presentLoading("Bumping tx..."); },
                onEnd: async () => { await dismissLoading(); },
                onFail: (err) => { toast.error(err); },
            },
            [(client) => client.BumpTx(req)]
        );
        if (res) {
            toast.success("Tx bump requested.");
            setTxid("");
            setOutputIndex("");
            setSatPerVbyte("");
        }
    };

    return (
        <IonContent className="ion-padding ion-content-no-footer">
            <IonCard>
                <IonCardHeader>
                    <IonCardTitle>Bump transaction fee (RBF)</IonCardTitle>
                </IonCardHeader>
                <IonCardContent>
                    <IonItem lines="none">
                        <IonInput
                            label="Txid"
                            labelPlacement="stacked"
                            value={txid}
                            onIonInput={(e) => setTxid(e.detail.value ?? "")}
                            placeholder="hex txid"
                            className="ion-margin-bottom"
                        />
                    </IonItem>
                    <IonItem lines="none">
                        <IonInput
                            label="Output index"
                            labelPlacement="stacked"
                            type="number"
                            min={0}
                            value={outputIndex}
                            onIonInput={(e) => setOutputIndex(e.detail.value ?? "")}
                            placeholder="0"
                        />
                    </IonItem>
                    <IonItem lines="none">
                        <IonInput
                            label="Sat per vB"
                            labelPlacement="stacked"
                            type="number"
                            min={0}
                            step="any"
                            value={satPerVbyte}
                            onIonInput={(e) => setSatPerVbyte(e.detail.value ?? "")}
                            placeholder="e.g. 10"
                        />
                    </IonItem>
                    <IonButton expand="block" onClick={bumpTx} disabled={!adminSource || !txid.trim() || outputIndex === "" || satPerVbyte === ""}>
                        <IonIcon icon={flashOutline} slot="start" /> Bump Tx
                    </IonButton>
                </IonCardContent>
            </IonCard>
        </IonContent>
    );
}

export default function AdminSwaps() {
    const [selectedView, setSelectedView] = useState("reverse");
    const admins = useAppSelector(selectAdminNprofileViews);
    const selectedId = useAppSelector(selectSelectedMetricsAdminSourceId);
    const adminSource = useMemo(
        () => admins.find(a => a.sourceId === selectedId),
        [admins, selectedId]
    );


    return <IonPage className="ion-page-width">
        <IonHeader className="ion-no-border">
            <MetricsSubPageToolbar title="Admin Swaps" />
        </IonHeader>
        <IonSegment value={selectedView} onIonChange={(e) => setSelectedView(e.detail.value?.toString() ?? "reverse")}>
            <IonSegmentButton value="reverse">
                <IonLabel>Reverse Swaps</IonLabel>
            </IonSegmentButton>
            <IonSegmentButton value="submarine">
                <IonLabel>Submarine Swaps</IonLabel>
            </IonSegmentButton>
            <IonSegmentButton value="bump">
                <IonLabel>Bump Tx</IonLabel>
            </IonSegmentButton>
        </IonSegment>
        {selectedView === "reverse" && <TxSwaps adminSource={adminSource} />}
        {selectedView === "submarine" && <SubmarineSwaps adminSource={adminSource} />}
        {selectedView === "bump" && <BumpTxSection adminSource={adminSource} />}
    </IonPage>;

}
