import { useEffect, useMemo, useState } from "react"
import { Period } from "@/Components/Dropdowns/LVDropdown"
import { toast } from "react-toastify";
import * as Types from '../../../Api/pub/autogenerated/ts/types';
import { IonButton, IonContent, IonItem, IonPage, IonHeader, useIonLoading, useIonRouter, IonRow, IonText, IonInput } from "@ionic/react";
import { flashOutline, linkOutline, personOutline } from "ionicons/icons";
import MetricsSubPageToolbar from "@/Layout2/Metrics/MetricsSubPageToolbar";
import { useAppSelector } from "@/State/store/hooks";
import { NprofileView, selectAdminNprofileViews } from "@/State/scoped/backups/sources/selectors";
import { selectSelectedMetricsAdminSourceId } from "@/State/runtime/slice";
import { TxSwapsList, TransactionSwapQuote } from "../../../Api/pub/autogenerated/ts/types";
import { fetcher, FetcherFuncs } from "../fetcher";
import AmountInput from "@/Components/AmountInput";

export default function TxSwaps({ adminSource }: { adminSource: NprofileView | undefined }) {
    const router = useIonRouter();
    const [amount, setAmount] = useState<string>("");
    const [quotes, setQuotes] = useState<TransactionSwapQuote[]>([]);
    const [address, setAddress] = useState<string>("");

    const [swaps, setSwaps] = useState<TxSwapsList>({ quotes: [], swaps: [] });
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)

    const [presentLoading, dismissLoading] = useIonLoading();

    const fetch = <T extends readonly unknown[]>(funcs: FetcherFuncs<T>, loadingMessage: string) => {
        if (!adminSource) return;
        return fetcher({ pubkey: adminSource.lpk, relays: adminSource.relays }, adminSource.keys, {
            onStart: async () => { setError(null); setLoading(true); await dismissLoading(); await presentLoading(loadingMessage); },
            onEnd: async () => { setLoading(false); await dismissLoading(); },
            onFail: (error) => { setError(error); toast.error(error); },
        }, funcs)
    }


    useEffect(() => {
        fetchSwaps()
    }, [adminSource?.sourceId])

    const fetchSwaps = async () => {
        const res = await fetch([(client) => client.ListAdminTxSwaps()], "Fetching swaps...")
        if (!res) return;
        const [swaps] = res
        setSwaps(swaps);
    }
    const requestQuote = async () => {
        const res = await fetch([(client) => client.GetAdminTransactionSwapQuotes({ transaction_amount_sats: +amount })], "Fetching quote...")
        if (!res) return;
        const [quote] = res
        setQuotes(quote.quotes);
    }

    const doSwap = async (swapOpId: string) => {
        if (!address) {
            toast.error("No address found");
            return;
        }
        const req: Types.PayAdminTransactionSwapRequest = { address, swap_operation_id: swapOpId }
        const res = await fetch([(client) => client.PayAdminTransactionSwap(req)], "Doing swap...")
        if (!res) return;
        fetchSwaps();
    }
    const cancelSwap = () => {
        setQuotes([]);
        fetchSwaps();
    }


    return <IonContent className="ion-padding ion-content-no-footer">
        {error && (
            <div style={{ color: "red", padding: 12 }}>
                <div style={{ fontWeight: 700, marginBottom: 8 }}>Something went wrong</div>
                <div style={{ opacity: 0.85, marginBottom: 12 }}>{error}</div>
                <div style={{ display: "flex", gap: 8 }}>
                    <IonButton onClick={() => void fetchSwaps()}>Retry</IonButton>
                    <IonButton fill="outline" onClick={() => router.push("/metrics/select", "back")}>
                        Change Source
                    </IonButton>
                </div>
            </div>
        )}
        {quotes.length === 0 && <>
            <IonRow className="ion-margin-top"> <IonText>Amount received by destination address</IonText></IonRow>
            <AmountInput
                displayValue={amount}
                effectiveSats={null}
                onType={(text) => { setAmount(text); return text; }}
                unit="sats"
                onToggleUnit={() => { }}
            />
            <IonButton onClick={requestQuote}>
                Request Quotes
            </IonButton>
        </>}
        {quotes.length > 0 && <IonRow><IonText className="ion-margin-top" style={{ fontSize: "1.2rem", fontWeight: "bold" }}>New Quotes</IonText></IonRow>}
        {quotes.length > 0 && quotes.map(quote => <div key={quote.swap_operation_id}>
            <IonRow> <IonText style={{ fontSize: "1.2rem", fontWeight: "bold" }}>Quote from {quote.service_url}</IonText></IonRow>
            <IonRow className="ion-margin-top"> <IonText>{quote.transaction_amount_sats} sats will be sent to address</IonText></IonRow>
            <IonRow  > <IonText>{quote.swap_fee_sats + quote.chain_fee_sats} sats will be paid for the swap</IonText></IonRow>
            <IonRow  > <IonText>{quote.service_fee_sats} sats will be paid for the service</IonText></IonRow>
            <IonRow className="ion-margin-top"> <IonText>{quote.service_fee_sats + quote.invoice_amount_sats} sats will be the total spent for the swap </IonText></IonRow>

            <IonRow className="ion-margin-top"> <IonText>Address to send to</IonText></IonRow>
            <IonInput
                label="Address"
                value={address}
                onIonChange={(e) => setAddress(e.detail.value || "")}
            />
            <IonButton onClick={() => doSwap(quote.swap_operation_id)}>Swap</IonButton>
        </div>)}
        {quotes.length > 0 && <IonButton onClick={cancelSwap}>Change Swap Amount</IonButton>}

        {swaps.quotes.length > 0 && <IonRow><IonText className="ion-margin-top" style={{ fontSize: "1.2rem", fontWeight: "bold" }}>Old Quotes</IonText></IonRow>}
        {swaps.quotes.map(quote => <div key={quote.swap_operation_id}>
            <IonRow> <IonText style={{ fontSize: "1.2rem", fontWeight: "bold" }}>Quote from {quote.service_url}</IonText></IonRow>
            <IonRow className="ion-margin-top"> <IonText>{quote.transaction_amount_sats} sats will be sent to address</IonText></IonRow>
            <IonRow  > <IonText>{quote.swap_fee_sats + quote.chain_fee_sats} sats will be paid for the swap</IonText></IonRow>
            <IonRow  > <IonText>{quote.service_fee_sats} sats will be paid for the service</IonText></IonRow>
            <IonRow className="ion-margin-top"> <IonText>{quote.service_fee_sats + quote.invoice_amount_sats} sats will be the total spent for the swap </IonText></IonRow>

            <IonRow className="ion-margin-top"> <IonText>Address to send to</IonText></IonRow>
            <IonInput
                label="Address"
                value={address}
                onIonChange={(e) => setAddress(e.detail.value || "")}
            />
            <IonButton onClick={() => doSwap(quote.swap_operation_id)}>Swap</IonButton>
        </div>)}
        {swaps.swaps.length > 0 && <IonRow><IonText className="ion-margin-top" style={{ fontSize: "1.2rem", fontWeight: "bold" }}>Swaps</IonText></IonRow>}
        {swaps.swaps.map(op => <div key={op.swap_operation_id}>
            <IonItem>
                {!op.failure_reason && <IonText>success: {op.operation_payment?.amount} sats to {op.address_paid}</IonText>}
                {op.failure_reason && <IonText>failed: {op.operation_payment?.amount} sats to {op.address_paid} reason: {op.failure_reason}</IonText>}
            </IonItem>
        </div>)}
    </IonContent>

}
