import { useCallback, useEffect, useMemo, useState } from "react";
import {
	IonContent,
	IonFab,
	IonFabButton,
	IonHeader,
	IonIcon,
	IonList,
	IonPage,
	IonRefresher,
	IonRefresherContent,
	IonSpinner,
	type RefresherEventDetail,
} from "@ionic/react";
import { add } from "ionicons/icons";
import OfferItem from "@/Components/OfferItem";
import type { OfferConfig } from "@/Api/pub/autogenerated/ts/types";
import { useOfferInfoModal } from "@/Components/Modals/OfferInfoModal";
import { SourceSelectionView } from "@/Components/Source/SourceSelectionView";
import { SourceReachabilityHint } from "@/Components/Source/SourceReachabilityHint";
import { useSourceSelectModal } from "@/Components/Source/SourceSelectSheet";
import EmptyState from "@/Components/common/ui/EmptyState";
import RootPageToolbar from "@/Layout2/RootPageToolbar";
import { useToast } from "@/lib/contexts/useToast";
import {
	useDeleteOfferMutation,
	useGetOffersQuery,
} from "@/State/api/offers";
import { selectFavoriteSourceId } from "@/State/scoped/backups/identity/slice";
import {
	type SourceView,
	selectSourceViews,
} from "@/State/scoped/backups/sources/selectors";
import { useAppSelector } from "@/State/store/hooks";

function pickDefaultOffersSource(
	sources: SourceView[],
	favoriteSourceId: string | null,
): SourceView {
	const favorite = sources.find((s) => s.sourceId === favoriteSourceId);
	if (favorite) return favorite;
	return sources[0];
}

export default function Offers() {
	const { showToast } = useToast();
	const sources = useAppSelector(selectSourceViews);
	const favoriteSourceId = useAppSelector(selectFavoriteSourceId);
	const sourceSelect = useSourceSelectModal();
	const askOfferInfo = useOfferInfoModal();

	const [selectedSourceId, setSelectedSourceId] = useState(
		() => pickDefaultOffersSource(sources, favoriteSourceId).sourceId,
	);

	useEffect(() => {
		if (!sources.some((s) => s.sourceId === selectedSourceId)) {
			setSelectedSourceId(
				pickDefaultOffersSource(sources, favoriteSourceId).sourceId,
			);
		}
	}, [sources, selectedSourceId, favoriteSourceId]);

	const selectedSource = useMemo(
		() =>
			sources.find((s) => s.sourceId === selectedSourceId) ??
			pickDefaultOffersSource(sources, favoriteSourceId),
		[sources, selectedSourceId, favoriteSourceId],
	);

	const {
		data: sourceOffers = [],
		isLoading,
		isError,
		error,
		refetch,
	} = useGetOffersQuery({ sourceId: selectedSource.sourceId });
	const [deleteOfferMutation] = useDeleteOfferMutation();

	const handleRefresh = useCallback(
		async (event: CustomEvent<RefresherEventDetail>) => {
			try {
				await refetch();
			} finally {
				event.detail.complete();
			}
		},
		[refetch],
	);

	const deleteOffer = async (offerId: string) => {
		const result = await deleteOfferMutation({
			sourceId: selectedSource.sourceId,
			offerId,
		});
		if (result.error) {
			showToast({
				message: result.error.message ?? "Failed to delete offer",
				color: "danger",
			});
			return;
		}
		showToast({
			message: "Offer deleted successfully",
			color: "success",
		});
	};

	const openForNew = () => {
		void askOfferInfo({ sourceId: selectedSource.sourceId });
	};
	const openForExisting = (offer: OfferConfig) => {
		void askOfferInfo({
			sourceId: selectedSource.sourceId,
			initialOffer: offer,
		});
	};

	return (
		<IonPage className="ion-page-width">
			<IonHeader className="ion-no-border">
				<RootPageToolbar title="Offers" />
			</IonHeader>
			<IonContent className="ion-padding">
				<IonRefresher slot="fixed" onIonRefresh={handleRefresh}>
					<IonRefresherContent />
				</IonRefresher>

				<div className="mx-auto flex min-h-full w-full max-w-md flex-col gap-6 pt-2">
					<div className="flex flex-col gap-2">
						<SourceSelectionView
							source={selectedSource}
							showBalance={false}
							onClick={() => {
								sourceSelect({
									sources,
									selectedSourceId,
									title: "Manage offers",
									showBalance: false,
								}).then((result) => {
									if (result.role === "confirm") {
										setSelectedSourceId(result.data.sourceId);
									}
								});
							}}
						/>
						<SourceReachabilityHint source={selectedSource} />
					</div>

					<section className="flex min-h-[40%] flex-1 flex-col">
						<p className="m-0 mb-3 text-xs font-medium uppercase tracking-wide text-muted">
							Offers
						</p>
						{isLoading ? (
							<div className="flex flex-1 items-center justify-center py-10">
								<IonSpinner name="crescent" />
							</div>
						) : isError ? (
							<EmptyState
								variant="section"
								title="Couldn't load offers"
								description={error?.message ?? "Failed to fetch offers"}
							/>
						) : sourceOffers.length === 0 ? (
							<EmptyState
								variant="section"
								title="No offers yet"
								description="Create an offer so others can pay this source."
							/>
						) : (
							<IonList lines="none" className="bg-transparent">
								{sourceOffers.map((offer) => (
									<OfferItem
										key={offer.offer_id}
										offer={{
											...offer,
											sourceId: selectedSource.sourceId,
										}}
										handleSelectOffer={openForExisting}
										onDelete={deleteOffer}
									/>
								))}
							</IonList>
						)}
					</section>
				</div>
				<IonFab slot="fixed" vertical="bottom" horizontal="end">
					<IonFabButton onClick={openForNew} aria-label="Create offer">
						<IonIcon icon={add} />
					</IonFabButton>
				</IonFab>
			</IonContent>
		</IonPage>
	);
}
