import type { ReactNode } from "react";
import moment from "moment";
import type { DebitRule } from "@/Api/pub/autogenerated/ts/types";
import { formatDebitRulesSummary, intervalLabel } from "@/lib/debit/rules";


function Highlight({ children }: { children: ReactNode }) {
	return (
		<span className="font-semibold text-[var(--ion-text-color)]">{children}</span>
	);
}

type Props = {
	rules: DebitRule[];
	className?: string;
};


export function DebitRulesSummary({ rules, className }: Props) {
	const summary = formatDebitRulesSummary(rules);
	const { frequencyRule, expirationRule } = summary;

	if (!frequencyRule && !expirationRule) {
		return (
			<p className={className ?? "text-sm text-secondary"}>
				<Highlight>Unlimited</Highlight> until revoked
			</p>
		);
	}

	const amountLabel = frequencyRule
		? new Intl.NumberFormat("en-US").format(frequencyRule.amount)
		: null;
	const windowLabel = frequencyRule
		? `${frequencyRule.numberOfIntervals} ${intervalLabel(
			frequencyRule.interval,
			frequencyRule.numberOfIntervals,
		).toLowerCase()}`
		: null;
	const expiresAt = expirationRule?.expiresAt ?? null;
	const expiresDateLabel = expiresAt
		? expiresAt.toLocaleString(undefined, {
			dateStyle: "medium",
			timeStyle: "short",
		})
		: null;
	const expiresRelativeLabel = expiresAt
		? moment(expiresAt).fromNow()
		: null;

	return (
		<div className={className ?? "flex flex-col gap-1 text-sm text-secondary"}>
			{frequencyRule && amountLabel && windowLabel ? (
				<p className="m-0">
					Up to <Highlight>{amountLabel} sats</Highlight> in any rolling{" "}
					<Highlight>{windowLabel}</Highlight>
				</p>
			) : null}
			{expirationRule && expiresDateLabel && expiresRelativeLabel ? (
				<p className="m-0">
					Expires <Highlight>{expiresDateLabel}</Highlight>{" "}
					({expiresRelativeLabel})
				</p>
			) : null}
		</div>
	);
}
