import { generatePrivateKey, getPublicKey } from 'nostr-tools'
import { NOSTR_PRIVATE_KEY_STORAGE_KEY, NOSTR_PUBLIC_KEY_STORAGE_KEY, NOSTR_PUB_DESTINATION, NOSTR_RELAYS } from '../constants'
import { NostrRequest } from './autogenerated/ts/nostr_transport'
import NewNostrClient from './autogenerated/ts/nostr_client'
import NostrHandler from './nostrHandler'
import { Buffer } from 'buffer'
import { bech32 } from 'bech32'
export const setNostrPrivateKey = () => {
    localStorage.setItem(NOSTR_PRIVATE_KEY_STORAGE_KEY, nostrPrivateKey || "")
    localStorage.setItem(NOSTR_PUBLIC_KEY_STORAGE_KEY, nostrPublicKey || "")
}
const getNostrPrivateKey = () => {
    return localStorage.getItem(NOSTR_PRIVATE_KEY_STORAGE_KEY)
}
let nostrPrivateKey = getNostrPrivateKey()
if (!nostrPrivateKey) {
    nostrPrivateKey = generatePrivateKey()
    // setNostrPrivateKey(nostrPrivateKey)
}
const nostrPublicKey = getPublicKey(Buffer.from(nostrPrivateKey, 'hex'))

const clients: Record<string, ReturnType<typeof NewNostrClient>> = {}

const parseNprofile = (nprofile: string) => {
    const { prefix, words } = bech32.decode(nprofile)
    if (prefix !== "nprofile") {
        throw new Error("invalid bech32 this is not a nprofile")
    }
    let profilePub = ""
    let relays = []
    let i = 0
    while (i < words.length) {
        const t = words[i]
        i++
        const l = words[i]
        i++
        const v = words.slice(i, i + l)
        i += l

        if (t === 0) {
            profilePub = Buffer.from(new Uint8Array(v)).toString('hex')
        } else if (t === 1) {
            relays.push(String.fromCharCode(...v))
        } else {
            console.log("unkown tlv")
        }
    }

    return { profilePub, relays }
}

export const getNostrClient = (nProfile: string) => {
    const { profilePub, relays } = parseNprofile(nProfile)
    const c = clients[profilePub]
    if (c) {
        return c
    }
    if (!relays) {
        throw new Error("cannot create client if no relays are provided")
    }
    clients[profilePub] = createNostrClient(profilePub, relays)
    return clients[profilePub]
}

const createNostrClient = (pubDestination: string, relays: string[]) => {
    const clientCbs: Record<string, (res: any) => void> = {}
    const handler = new NostrHandler({
        privateKey: nostrPrivateKey!,
        publicKey: nostrPublicKey,
        relays
    }, e => {
        const res = JSON.parse(e.content) as { requestId: string }
        if (clientCbs[res.requestId]) {
            console.log("cb found")
            const cb = clientCbs[res.requestId]
            cb(res)
            delete clientCbs[res.requestId]
        } else {
            console.log("cb not found")
        }
    })
    const clientSend = (to: string, message: NostrRequest): Promise<any> => {
        console.log("sending to", to, message)
        if (!message.requestId) {
            message.requestId = makeId(16)
        }
        const reqId = message.requestId
        if (clientCbs[reqId]) {
            throw new Error("request was already sent")
        }
        handler.Send(to, JSON.stringify(message))
        return new Promise(res => {
            clientCbs[reqId] = (response: any) => {
                res(response)
            }
        })
    }
    return NewNostrClient({
        retrieveNostrUserAuth: async () => { return nostrPublicKey },
        pubDestination,
    }, clientSend)
}



function makeId(length: number) {
    var result = '';
    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for (var i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}

//@ts-ignore use this to have access to the client from the console
// global.nostr = nostr // TODO: remove,DEV ONLY