import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import type { BeaconData } from "@/Api/pub/autogenerated/ts/types";
import { getPersistConfigKey, makeScopedPersistedReducer } from "@/State/scope/buildPersistedScopedReducer";
import { createEncryptedScopedStorage } from "@/storage/encryptedScopedStorage";
import { canonicalRelayUrl } from "./relays";
import {
	beaconLookupKey,
	beaconLookupsAdapter,
	beaconNodesAdapter,
	BeaconLookup,
	getInitialBeaconsState,
} from "./state";
import type { RootState } from "@/State/store/store";
import { selectScopedStrict } from "@/State/scope/stricScopedSelector";

export const beaconsSlice = createSlice({
	name: "beacons",
	initialState: getInitialBeaconsState(),
	reducers: {
		recordBeacon(
			state,
			a: PayloadAction<{
				lpk: string;
				relay: string;
				seenAtMs: number;
				data: BeaconData;
			}>,
		) {
			const relay = canonicalRelayUrl(a.payload.relay);
			if (!relay) return;

			const { lpk, seenAtMs, data } = a.payload;
			const existing = state.nodes.entities[lpk];
			const prevSeen = existing?.relays[relay]?.lastSeenAtMs ?? 0;
			if (prevSeen >= seenAtMs) return;

			if (!existing) {
				beaconNodesAdapter.upsertOne(state.nodes, {
					lpk,
					name: data.name,
					avatarUrl: data.avatarUrl,
					fees: data.fees,
					nextRelay: data.nextRelay,
					relays: { [relay]: { lastSeenAtMs: seenAtMs } },
				});
				return;
			}

			const maxSeen = Math.max(0, ...Object.values(existing.relays).map(r => r.lastSeenAtMs));
			const relays = {
				...existing.relays,
				[relay]: { lastSeenAtMs: seenAtMs },
			};

			beaconNodesAdapter.upsertOne(state.nodes, {
				...existing,
				relays,
				...(seenAtMs >= maxSeen
					? {
						name: data.name,
						avatarUrl: data.avatarUrl,
						fees: data.fees,
						nextRelay: data.nextRelay,
					}
					: {}),
			});
		},

		startLookups(
			state,
			a: PayloadAction<{
				pairs: { lpk: string; relay: string }[];
				epoch: number;
			}>,
		) {
			const { pairs, epoch } = a.payload;
			const updates: BeaconLookup[] = [];
			for (const pair of pairs) {
				const relay = canonicalRelayUrl(pair.relay);
				if (!relay) continue;
				updates.push({
					id: beaconLookupKey(pair.lpk, relay),
					lpk: pair.lpk,
					relay,
					epoch,
					status: "probing",
				});
			}
			if (updates.length) beaconLookupsAdapter.upsertMany(state.lookups, updates);
		},

		finishLookup(
			state,
			a: PayloadAction<{ lpk: string; relay: string; epoch: number }>,
		) {
			const relay = canonicalRelayUrl(a.payload.relay);
			if (!relay) return;
			const id = beaconLookupKey(a.payload.lpk, relay);
			const p = state.lookups.entities[id];
			if (!p || p.epoch !== a.payload.epoch) return;
			p.status = "done";
		},

		dropLpks(state, a: PayloadAction<{ lpks: string[] }>) {
			const { lpks } = a.payload;
			if (!lpks.length) return;
			const drop = new Set(lpks);
			beaconNodesAdapter.removeMany(state.nodes, lpks);
			const lookupIds = state.lookups.ids.filter(id => {
				const lpk = state.lookups.entities[id]?.lpk;
				return !!lpk && drop.has(lpk);
			});
			beaconLookupsAdapter.removeMany(state.lookups, lookupIds);
		},
	},
});

const persistKey = "__beacons";

export function getScopedBeaconsReducer(identityPubkey: string, DataKey: CryptoKey) {
	return makeScopedPersistedReducer(
		beaconsSlice.reducer,
		persistKey,
		identityPubkey,
		{
			version: 0,
			storage: createEncryptedScopedStorage({
				identityId: identityPubkey,
				sliceName: beaconsSlice.name,
				dataKey: DataKey,
			}),
			blacklist: ["lookups"],
		},
	);
}

export function getScopedBeaconsPersistKey(identityPubkey: string) {
	return getPersistConfigKey(persistKey, identityPubkey);
}

export const beaconsActions = beaconsSlice.actions;

export const beaconNodesSelectors = beaconNodesAdapter.getSelectors<RootState>(
	(state) => selectScopedStrict(state).beacons.nodes
);

export const beaconLookupsSelectors = beaconLookupsAdapter.getSelectors<RootState>(
	(state) => selectScopedStrict(state).beacons.lookups
);
