import { createEntityAdapter, EntityState } from "@reduxjs/toolkit";
import type { CumulativeFees } from "@/Api/pub/autogenerated/ts/types";

export { BEACON_STALE_OLDER_THAN } from "@/constants";


export type BeaconLookupStatus = "probing" | "done";

export type BeaconRelayPresence = {
	lastSeenAtMs: number;
};

export type BeaconNode = {
	lpk: string;
	name?: string;
	avatarUrl?: string;
	fees?: CumulativeFees;
	nextRelay?: string;
	relays: Record<string, BeaconRelayPresence>;
};

export type BeaconLookup = {
	id: string;
	lpk: string;
	relay: string;
	epoch: number;
	status: BeaconLookupStatus;
};

export const beaconNodesAdapter = createEntityAdapter<BeaconNode, string>({
	selectId: (n) => n.lpk,
});

export const beaconLookupsAdapter = createEntityAdapter<BeaconLookup, string>({
	selectId: (l) => l.id,
});

export type BeaconsState = {
	nodes: EntityState<BeaconNode, string>;
	lookups: EntityState<BeaconLookup, string>;
};

export const getInitialBeaconsState = (): BeaconsState => ({
	nodes: beaconNodesAdapter.getInitialState(),
	lookups: beaconLookupsAdapter.getInitialState(),
});

export const beaconLookupKey = (lpk: string, relay: string) => `${lpk}\0${relay}`;
