import { createApi, fakeBaseQuery } from "@reduxjs/toolkit/query/react";
import type { DebitAuthorization } from "@/Api/pub/autogenerated/ts/types";
import { getNostrClient } from "@/Api/nostr";
import { selectHealthyNprofileSourceViewById } from "@/State/scoped/backups/sources/selectors";
import type { RootState } from "@/State/store/store";
import {
	fetchProfile,
	normalizeRelays,
	type NostrProfile,
	verifyNip05Claim,
} from "../../lib/profile";

const ONE_HOUR_SECONDS = 60 * 60;

export type GetDebitAuthorizationsArg = {
	sourceId: string;
};

export const appApi = createApi({
	reducerPath: "appApi",
	baseQuery: fakeBaseQuery(),
	tagTypes: ["DebitAuthorizations"],
	endpoints: (b) => ({
		getProfile: b.query<NostrProfile | null, { pubkey: string; relays: string[] }>({
			serializeQueryArgs: ({ queryArgs }) => ({
				pubkey: queryArgs.pubkey,
				relays: normalizeRelays(queryArgs.relays),
			}),
			queryFn: async ({ pubkey, relays }) => {
				try {
					const profile = await fetchProfile(pubkey, relays);
					return { data: profile };
				} catch (e: unknown) {
					const message = e instanceof Error ? e.message : "failed";
					return { error: { status: "CUSTOM_ERROR", error: message } };
				}
			},
		}),
		verifyNip05: b.query<boolean, { pubkey: string; nip05: string }>({
			keepUnusedDataFor: ONE_HOUR_SECONDS,
			queryFn: async ({ pubkey, nip05 }) => {
				try {
					const verification = await verifyNip05Claim(pubkey, nip05);
					return { data: verification };
				} catch (e: unknown) {
					const message = e instanceof Error ? e.message : "failed";
					return { error: { status: "CUSTOM_ERROR", error: message } };
				}
			},
		}),
		getDebitAuthorizations: b.query<
			DebitAuthorization[],
			GetDebitAuthorizationsArg
		>({
			providesTags: (_result, _error, { sourceId }) => [
				{ type: "DebitAuthorizations", id: sourceId },
			],
			queryFn: async ({ sourceId }, api) => {
				const state = api.getState() as RootState;
				const source = selectHealthyNprofileSourceViewById(state, sourceId);
				if (!source) {
					return {
						error: {
							status: "CUSTOM_ERROR",
							error: "Source is not available",
						},
					};
				}

				try {
					const client = await getNostrClient(
						{ pubkey: source.lpk, relays: source.relays },
						source.keys,
					);
					const res = await client.GetDebitAuthorizations();
					if (res.status !== "OK") {
						return {
							error: {
								status: "CUSTOM_ERROR",
								error: res.reason || "Could not load debit authorizations",
							},
						};
					}
					return { data: res.debits };
				} catch (e: unknown) {
					const message =
						e instanceof Error
							? e.message
							: "Could not load debit authorizations";
					return { error: { status: "CUSTOM_ERROR", error: message } };
				}
			},
		}),
	}),
});

export const {
	useGetProfileQuery,
	useVerifyNip05Query,
	useGetDebitAuthorizationsQuery,
	useLazyGetDebitAuthorizationsQuery,
} = appApi;
