import { getNostrClient } from "@/Api/nostr";
import { createDeferred } from "@/lib/deferred";
import type { ShowToast } from "@/lib/contexts/useToast";
import type { Satoshi } from "@/lib/types/units";
import { formatSatoshi } from "@/lib/units";
import {
	InputClassification,
	type ParsedInput,
	type ParsedInvoiceInput,
	type ParsedLightningAddressInput,
	type ParsedLnurlPayInput,
	type ParsedNofferInput,
} from "@/lib/types/parse";
import { historyFetchSourceRequested } from "@/State/listeners/actions";
import { AppThunk, AppThunkDispatch } from "@/State/store/store";
import { TaskResult } from "@reduxjs/toolkit";
import { UserOperation } from "@/Api/pub/autogenerated/ts/types";
import { SourceType } from "../schema";
import { NprofileView, selectSourceViewById } from "../selectors";
import { sourcesActions } from "../slice";
import { makeKey, payInvoiceReponseToUserOperation } from "./helpers";
import type { SourceOptimsiticInvoice } from "./types";

export type InvoicePaymentSource =
	| ParsedNofferInput
	| ParsedLnurlPayInput
	| ParsedLightningAddressInput;

export const sendInvoicePayment = ({
	sourceId,
	parsedInvoice,
	amount,
	note,
	invoiceSource,
	showToast,
}: {
	sourceId: string;
	parsedInvoice: ParsedInvoiceInput;
	amount: Satoshi;
	note?: string;
	invoiceSource?: InvoicePaymentSource;
	showToast: ShowToast;
}): AppThunk<void> => {
	return (dispatch, getState) => {
		const selectedSource = selectSourceViewById(getState(), sourceId);
		if (!selectedSource || selectedSource.type !== SourceType.NPROFILE_SOURCE) {
			throw new Error("Source not found or is not nprofile");
		}

		const operationId = parsedInvoice.data;
		const optimisticOperation: SourceOptimsiticInvoice = {
			optimistic: true,
			sourceId,
			operationId,
			opKey: makeKey(sourceId, operationId),
			amount,
			paidAtUnix: Date.now(),
			type: "INVOICE",
			inbound: false,
			invoice: parsedInvoice.data,
			invoiceMemo: parsedInvoice.memo,
			invoiceSource,
			memo: note,
		};

		dispatch(sourcesActions.addOptimistic({
			sourceId: selectedSource.sourceId,
			operation: optimisticOperation,
		}));

		void payInvoice({
			dispatch,
			selectedSource,
			parsedInvoice,
			optimisticOperation,
			amount,
			showToast,
		});
	};
};

async function payInvoice({
	dispatch,
	selectedSource,
	parsedInvoice,
	optimisticOperation,
	amount,
	showToast,
}: {
	dispatch: AppThunkDispatch;
	selectedSource: NprofileView;
	parsedInvoice: ParsedInvoiceInput;
	optimisticOperation: SourceOptimsiticInvoice;
	amount: Satoshi;
	showToast: ShowToast;
}) {
	const optimisticOperationId = optimisticOperation.operationId;
	try {
		const res = await (await getNostrClient(
			{ pubkey: selectedSource.lpk, relays: selectedSource.relays },
			selectedSource.keys,
		)).PayInvoice({
			invoice: parsedInvoice.data,
			amount: 0,
		});
		if (res.status !== "OK") {
			throw new Error(res.reason);
		}

		handlePaymentSuccess(
			dispatch,
			amount,
			selectedSource,
			payInvoiceReponseToUserOperation(res, optimisticOperation),
			showToast,
		);

		const deferred = createDeferred<TaskResult<void>>();
		dispatch(historyFetchSourceRequested({
			sourceId: selectedSource.sourceId,
			deferred,
		}));
	} catch (err) {
		handlePaymentError(err, dispatch, selectedSource.sourceId, optimisticOperationId, showToast);
	}
}

function handlePaymentError(
	err: unknown,
	dispatch: AppThunkDispatch,
	sourceId: string,
	optimisticOpId: string,
	showToast: ShowToast,
) {
	console.error(err);
	dispatch(sourcesActions.removeOptimistic({ sourceId, operationId: optimisticOpId }));
	showToast({
		message: err instanceof Error ? err.message : "Payment failed",
		color: "danger",
	});
}

function handlePaymentSuccess(
	dispatch: AppThunkDispatch,
	amount: Satoshi,
	selectedSource: NprofileView,
	operation: UserOperation,
	showToast: ShowToast,
) {
	dispatch(sourcesActions.ingestLive({
		sourceId: selectedSource.sourceId,
		operation,
	}));
	showToast({
		message: `Payment of ${formatSatoshi(amount)} sats sent`,
		color: "success",
	});
}

export function invoiceSourceFromParsed(parsed: ParsedInput): InvoicePaymentSource | undefined {
	switch (parsed.type) {
		case InputClassification.NOFFER:
		case InputClassification.LNURL_PAY:
		case InputClassification.LN_ADDRESS:
			return parsed;
		default:
			return undefined;
	}
}
