import React, { useCallback, useEffect, useState } from "react";
import { Modal } from "../../Components/Modals/Modal";
import { UseModal } from "../../Hooks/UseModal";
import { selectNostrSpends, useSelector } from "../../State/store";
import { getNostrClient, parseNprofile } from "../../Api/nostr";
import { DebitAuthorization, LiveDebitRequest, LiveDebitRequest_debit_type } from "../../Api/pub/autogenerated/ts/types";
import { SourceDebitRequest, SpendFrom } from "../../globalTypes";

export const LinkedApp = () => {
  const { isShown, toggle } = UseModal();
  //const [requestData, setRequestData] = useState<SourceDebitRequest | null>(null);
  const [debitAuthorizations, setDebitAuthorizations] = useState<(DebitAuthorization & { source: SpendFrom })[]>([])
  const nodedUp = useSelector(state => state.nostrPrivateKey);
  const nostrSpends = useSelector(selectNostrSpends);
  //const [updatehook, setUpdateHook] = useState(0)
  const fetchAuths = useCallback(() => {
    nostrSpends.forEach(source => {
      const { pubkey, relays } = parseNprofile(source.pasteField)
      getNostrClient({ pubkey, relays }, source.keys).then(c => {
        c.GetDebitAuthorizations().then(res => {
          if (res.status === "OK") {
            setDebitAuthorizations((state) => [
              ...state,
              ...res.debits.filter(
                debit => !state.some(stateDebt => stateDebt.debit_id === debit.debit_id)
              ).map(debit => ({ ...debit, source })),
            ])
          }
        })

      })
    });
  }, [nostrSpends])
  useEffect(() => {
    if (!nodedUp) {
      return;
    }
    fetchAuths()
  }, [fetchAuths, nodedUp, /* updatehook */])

  const resetAuth = useCallback(async (request: { source: SpendFrom, npub: string }) => {
    const res = await (await getNostrClient(request.source.pasteField, request.source.keys)).ResetDebit({ npub: request.npub });
    if (res.status !== "OK") {
      throw new Error(res.reason);
    }
    fetchAuths()
  }, [toggle, fetchAuths])

  return (
    <div className="LinkedApp_container">
      <div className="LinkedApp">
        <div className="LinkedApp_header_text">Linked Apps</div>
        <div>
          {debitAuthorizations.map(res => (
            <div key={res.debit_id}>
              {!res.authorized && <span>BANNED</span>}
              <span>{res.npub}</span>
              <button onClick={() => resetAuth({ source: res.source, npub: res.npub })}>RESET</button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

